### ISSUE TITLE
TypeDoc lint tool

### ISSUE THREAD

**Issue by marcelovicentegc** [vtex/shoreline#1371]
# TypeDoc lint tool

We use TypeDoc to generate documentation from our code. To ensure the greater developer experience and delivery quality, we should place a TypeDoc linting tool to check whether new components are being shipped with documentation or not. This tool should check for the existence of TypeDocs on new interfaces, types, components, functions, etc. 

Our linting configuration should follow the [Documentation development guideline](#1305) rules.

Related to #1290

**Comment by matheusps** [comment]
Not needed. We are not using typedoc anymore
