### ISSUE TITLE
Storybook: Improve DX to create playgrounds and auto-export to docs

### ISSUE THREAD

**Issue by marcelovicentegc** [vtex/shoreline#1394]
The goal of this task is to investigate and come up with the best way to organize storybook stories into a meaningful way. 

### Proposal

1) Each component has a non-interactive Examples story, where use cases are implemented
2) Each component has a interactive Playground story, where users can play with each property of the component 

Take #1384 as an example of an Examples story.

### How do we benefit from this approach?

1) We can create component templates based on their available and implemented use cases. This can help developers to speed up the development of their apps, and also standardize these use cases.
2) The playgrounds can be utilized as actual playgrounds on our documentation website. This is a huge win since developing our own playground solution would take a lot of our time. Instead, we can just embed the component's Playground story into our docs, programatically with the docs-generator.

**Comment by lucasaarcoverde** [comment]
Issue already resolved with the implementation of code preview on the documentation site and the definition of storybook structure
