### ISSUE TITLE
Virtual: Fixed component exceeds maximum update stack when stateful

### ISSUE THREAD

**Issue by marcelovicentegc** [vtex/shoreline#1449]
Take a look at the changes from https://github.com/vtex/shoreline/pull/1448, which fixes a broken virtual component story (fixed). It exceeds the maximum update stack when the `overscan` property is set while having some kind of state like:

```jsx
style={{
   background: index % 2 !== 0 ? 'gray' : 'white',
}}
```

**Comment by davicostalf** [comment]
Virtual component no longer exists, so I'm closing this.
