### ISSUE TITLE
Collection: differences from figma specs

### ISSUE THREAD

**Issue by talitagaldino** [vtex/shoreline#1508]
# Collection

Collection components are implemented differently from the Figma definition

### Figma

![image](https://github.com/vtex/shoreline/assets/42968281/5f29f559-1247-4bda-abcc-2b4c966f264c)
![image](https://github.com/vtex/shoreline/assets/42968281/bd1af41f-6452-4cd4-997e-58cfe1f947ff)
![image](https://github.com/vtex/shoreline/assets/42968281/9bf2a274-1a14-4cb4-8f39-69bdec6522ca)

### Implementation
![image](https://github.com/vtex/shoreline/assets/42968281/7a5696ef-9291-444a-a429-3c95be4478e6)
![image](https://github.com/vtex/shoreline/assets/42968281/95ca02a4-43ad-4706-a2a7-381f054de48a)
![image](https://github.com/vtex/shoreline/assets/42968281/801f12e0-2691-4ff4-beb4-741e03d67005)

**Comment by beatrizmilhomem** [comment]
Storybook already has the examples that were missing and spaces are correct. I'm closing this issue.
