### ISSUE TITLE
Links and images missing in the documentation website

### ISSUE THREAD

**Issue by beatrizmilhomem** [vtex/shoreline#1598]
### Summary

Some links and images are missing.

### Suggested solution

**All Components:**
- Change`ToastStack` card to `Toast` and link to https://shoreline.vtex.com/components/toast
- Add a `RadioGroup` card and link to https://shoreline.vtex.com/components/checkbox/checkbox-group
- Add a `CheckboxGroup` card and link to https://shoreline.vtex.com/components/radio/radio-group
- Fix link of the `ComboboxInput` https://shoreline.vtex.com/components/combobox/combobox-input
- Update Checkbox and Radio images.

**Alert:**
- In the `Related components` section, change`ToastStack` card to `Toast` and link to the page https://shoreline.vtex.com/components/toast

**Checkbox:**
- Add a `Related components` section, including RadioGroup and CheckboxGroup.

**CheckboxGroup:**
- Add image to the RadioGroup card in related components.

**ConfirmationModal:**
- In the `Related components` section, change`ToastStack` card to `Toast` and link to the page https://shoreline.vtex.com/components/toast

**Input:**
- Add a `Related components` section, including Textarea, DatePicker, and Search.

**Modal:**
- In the `Related components` section, change`ToastStack` card to `Toast` and link to the page https://shoreline.vtex.com/components/toast

**Radio:**
- Remove the `Related components` section.

**RadioGroup:**
- Add a `Related components` section, including Select and CheckboxGroup.

**Select:**
- Add images to the RadioGroup and CheckboxGroup cards in the related components.
- Link RadioGroup card to https://shoreline.vtex.com/components/radio/radio-group
- Link CheckboxGroup card to https://shoreline.vtex.com/components/checkbox/checkbox-group

**Tab:**
- In related components, change image in the RadioGroup card and link to https://shoreline.vtex.com/components/radio/radio-group

**TimeInput:**
- Add a `Related components` section, including DatePicker, DateRangePicker, Input, and Select.

**Navigation:**
- Move the Date group above the Primitives group.
<img width="289" alt="image" src="https://github.com/vtex/shoreline/assets/84085258/3525ba6c-e57d-4f0d-90cf-da34de7d684b">

**Images**

![all-checkbox-group](https://github.com/vtex/shoreline/assets/84085258/933c0970-0fdd-4649-bbd9-01f755be3993)
![all-checkbox](https://github.com/vtex/shoreline/assets/84085258/afec64bf-5f5d-415e-87f5-8b410999803a)
![all-radio-group](https://github.com/vtex/shoreline/assets/84085258/967aa36e-f54b-47fe-9336-ca6ecee014ef)
![all-radio](https://github.com/vtex/shoreline/assets/84085258/ced14108-e54e-4dad-abc4-0761d90100de)

**Comment by kevinch** [comment]
Iniciei um PR nesse sentido ontem gente: https://github.com/vtex/shoreline/pull/1762

Posso seguir olhando o detalhe da issue para tentar fechar todos os pontos.

**Comment by beatrizmilhomem** [comment]
@kevinch aprovei as primeiras mudanças nesse seu PR. Se vc puder seguir com os outros ajustes, será ótimo!

**Comment by kevinch** [comment]
New branch: https://github.com/vtex/shoreline/pull/1875

Had to switch due to some local issues with the docs:build

**Comment by kevinch** [comment]
@davicostalf if the issue of the links was on https://shoreline.vtex.com/guides/contributing-introduction then it's been fixed.

**Comment by kevinch** [comment]
PR ready for review.
