### ISSUE TITLE
ToastStack: no toast cleanup

### ISSUE THREAD

**Issue by rafarubim** [vtex/shoreline#1605]
### Summary

Shoreline uses a static-global-variable approach to keep toast state, but does not provide a way to clean current toasts.

The `react-hot-toast` library does provide a way to [dismiss toasts programatically](https://react-hot-toast.com/docs/toast#:~:text=Dismiss%20toast%20programmatically), but Shoreline does not reexport it.

The lack of this important feature currently makes us unable to cleanup any test code that uses the `ToastStack` component. Example:

```tsx
// If it was possible, cleanup code would be here
// beforeEach(() => {
//   toast.remove()
// })

it('Shows toast after button is pressed', async () => {
  const user = userEvent.setup()
  render(
    <ToastStack>
      <button onClick={() => toast.success('Success!')}>Show toast</button>
    </ToastStack>
  )
  
  const button = screen.getByRole('button', { name: 'Show toast' })
  await user.click(button)
  await waitFor(() => {
    expect(screen.queryByText('Success!')).toBeVisible()
  })
})

it('Does not show toast from previous test LOL', async () => {
  render(
    <ToastStack /> // ToastStack component uses a static global variable to store toast state.
    // Therefore, this renders the "Success!" from the previous test
    // (which is bad and there's no way to run cleanup code)
  )
  
  // This test fails because "Success" is actually visible
  expect(screen.queryByText('Success!')).not.toBeInTheDocument()
})
```

### Package

@vtex/shoreline

### Package Manager

yarn

**Comment by viniciuslagedo** [comment]
Also, the dismiss method can be used to dismiss a specific toast, which is helpful if you want to dismiss a loading toast with infinite duration.
