### ISSUE TITLE
GH Projects Test

### ISSUE THREAD

**Issue by marcelovicentegc** [vtex/shoreline#1627]
### Summary

Last time I checked, the auto-add wasn't toggled.

### Expected behavior

Is it now, though? This issue should appear on the GH Projects backlog.

### Current behavior

Wrap animated gifs/videos in a details tag:
<details>
  <summary>Summary of your gif(s)</summary>
  <img src="..." alt="Description of what the gif shows">
</details>

### Reproducible Example

:thinking_face:

### Suggested solution

Enable auto-add

### Package

@vtex/shoreline, @vtex/shoreline-ts-table, @vtex/shoreline-stylelint, @vtex/shoreline-icons

### Package Manager

pnpm

**Comment by lucasaarcoverde** [comment]
All good now!
