### ISSUE TITLE
Prototype connections in Figma components

### ISSUE THREAD

**Issue by beatrizmilhomem** [vtex/shoreline#1695]
### Problem

Currently, we recommend connecting the component variants in a prototype whenever it makes sense (default state with the hover state, hover with pressed/focus state, focus with filled). But, when using those components in prototyping a flow for user testing, it can get painful to remove the components' prototypes so the test can work correctly.

### Questions

Should we maintain only the `default` with `hover` prototypes in components?
Should a component prototype be complete, including all possible interactions that make sense?
Is it really painful to deal with those prototypes when creating flows for user testing? What do other designers think?

### References

@davicostalf brought up this pain point from when he was prototyping for a user test. He had a lot of issues with components while applying the tests.

@felipepowlist missed inputs, checkboxes, and radios being clickable. https://github.com/vtex/shoreline/issues/1744

**Comment by beatrizmilhomem** [comment]
Next step: Review components prototypes and maintain only the hover interaction.

**Comment by davicostalf** [comment]
Released in the last Figma library update.
