### ISSUE TITLE
Add mouse leave event to pressed state of Button and IconButton

### ISSUE THREAD

**Issue by davicostalf** [vtex/shoreline#1701]
### Problem

In Figma, when assembling prototypes, sometimes buttons stay stuck in the pressed state after an action has been triggered. This may be due to a bug in Figma.

### Solution

The best solution I could find is adding a mouse leave event to the pressed state that links to the default state.

### Usage examples

I've already applied this interaction to the normal-sized secondary and tertiary IconButton.

### References

https://forum.figma.com/t/while-pressing-state-doesnt-reset-after-overlay-is-closed/3226

**Comment by beatrizmilhomem** [comment]
I think this goes against the issue https://github.com/vtex/shoreline/issues/1695.
Shouldn't the mouse leave event be applied only when prototyping a flow instead of in the component itself?

**Comment by beatrizmilhomem** [comment]
@davicostalf what do you think? ☝️

**Comment by davicostalf** [comment]
Closing this issue since the topic is already being discussed in #1695.
