### ISSUE TITLE
Search placeholder is not localizated

### ISSUE THREAD

**Issue by lafray** [vtex/shoreline#1705]
Who can be see in [this code line](https://github.com/vtex/shoreline/blob/3c4958d6a9f7112b638ff7b774cd9c002942a6b9/packages/shoreline/src/components/search/search.tsx#L20) the placehoder `"Search"` in the `Search` component is fixed and do not changes according to the language.

**Comment by lucasaarcoverde** [comment]
If I'm not mistaken, the idea is that the translation should be responsibility from the application. Is that right @beatrizmilhomem @davicostalf? Or should we have a default translated placeholder?

**Comment by lafray** [comment]
> If I'm not mistaken, the idea is that the translation should be responsibility from the application. Is that right @beatrizmilhomem @davicostalf? Or should we have a default translated placeholder?

My big point is that other shoreline components take care of translating your text. I think this difference can generate misuse, where people don't realize that it is not translated

**Comment by lucasaarcoverde** [comment]
that's true @lafray, I agree with you on that! IMO we should remove the default label or add the translation. @beatrizmilhomem @davicostalf what's the best approach from the design perspective?

**Comment by davicostalf** [comment]
The requirement for this component is that there should be a default placeholder that is localized ("Search") and it should be possible to pass a customized message ("Search by name or ID").

**Comment by beatrizmilhomem** [comment]
This looks ready to be moved to the Backlog.

---

### Summary
Fix the **Search** component placeholder.
- [ ] Default placeholder that is localized ("Search")
- [ ] Still allow to pass a customized message (for example, "Search by name or ID")
