### ISSUE TITLE
Add help text at Radio item

### ISSUE THREAD

**Issue by luarakerlen** [vtex/shoreline#1706]
### Summary

I need to design a forms where radio items has a help text.
My suggestion is to add this as optional prop, because I believe this can be useful for other applications.

<img width="325" alt="image" src="https://github.com/vtex/shoreline/assets/26902816/5bc01773-38a5-48c3-8fba-e07023b18b83">

**Comment by lucasaarcoverde** [comment]
You already can do this behavior using `Field` components, something like that:

```jsx
<Field>
  <Radio value="daily">Daily</Radio>
  <FieldDescription>1 Row per day per entity</FieldDescription>
</Field>
```

But the design is a little bit different from the one you just sent here. @beatrizmilhomem can you take a look on this?
<img width="182" alt="Screenshot 2024-07-09 at 13 11 25" src="https://github.com/vtex/shoreline/assets/20579226/101d3c61-899b-4afd-917b-49ae71d62661">

[you can check on this sandbox for implementation details](https://codesandbox.io/p/sandbox/shoreline-radio-field-rzq944?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyellg8500063b6jkev8e4h8%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyellg8500023b6j4urdk3l4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyellg8500033b6johig8p6y%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyellg8500053b6j83oosst1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyellg8500023b6j4urdk3l4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyellg8400013b6jqz4wvul6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clyellg8500023b6j4urdk3l4%2522%252C%2522activeTabId%2522%253A%2522clyellg8400013b6jqz4wvul6%2522%257D%252C%2522clyellg8500053b6j83oosst1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyellg8500043b6juhwma37a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clyellg8500053b6j83oosst1%2522%252C%2522activeTabId%2522%253A%2522clyellg8500043b6juhwma37a%2522%257D%252C%2522clyellg8500033b6johig8p6y%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clyellg8500033b6johig8p6y%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by davicostalf** [comment]
Lua had asked me before and I had forgotten about the Field component. That answers it, I believe.

Regarding the layout, the label in this case was omitted because there's a form section dedicated for this field. This makes sense sometimes.
