### ISSUE TITLE
Some interactions on Figma components are not working as expected

### ISSUE THREAD

**Issue by felipepowlist** [vtex/shoreline#1744]
### Problem

Some components interactions are not working as expected:

**Select**
<img width="893" alt="Captura de Tela 2024-07-19 às 10 38 32" src="https://github.com/user-attachments/assets/a1c0a777-30bf-4884-bf67-8383b144b55a">
There's too much space between the dropdown and the input

**Inputs in general**
- are not clickable
- the blinking indicator is not blinking

**Checkbox and radio**
- Are not clickable

### Expected behavior

I expected them to work the way Admin UI library works

### Suggested solution

Prototype interactions directly on library components

### Package Manager

pnpm

**Comment by lucasaarcoverde** [comment]
@felipepowlist can you provide a reproducible example?

**Comment by felipepowlist** [comment]
<img width="840" alt="Captura de Tela 2024-07-22 às 10 30 10" src="https://github.com/user-attachments/assets/bbcd189a-53d4-4019-b52e-32f1fa5350b9">
I think I understood the select problem. It happens when we remove the label. Here's a prototype:

https://www.figma.com/proto/7ycgXpOdzSJ1i3T0wDvHTq/Usability-test-Prototype?page-id=49%3A32050&node-id=49-32051&viewport=928%2C293%2C1&t=3jKYyxdfa3E7GCul-1&scaling=min-zoom&content-scaling=fixed

About the blinking cursor, I don't know what's happening. Sometimes it works, sometimes it doesn't.

About not having the interactions built in, I can see how this can be helpful in some cases but painful in others. In my case now it would help me a lot. I am recreating the components in my file to make it work the way I need. Maybe we should discuss this in more detail with the team.

**Comment by davicostalf** [comment]
@beatrizmilhomem I think we should open a discussion with designers around their experience with component prototypes.

**Comment by beatrizmilhomem** [comment]
Since we are discussing two different subjects, I'll separate them into different issues. :)
About component prototypes, we can go on with the discussion in the existing issue https://github.com/vtex/shoreline/issues/1695.
And it looks like the blinking cursor is a Figma bug, so we'll keep it as it is for now.
