### ISSUE TITLE
Color documentation: semantic tokens should come first

### ISSUE THREAD

**Issue by davicostalf** [vtex/shoreline#1764]
### Problem

Primitive tokens are the first ones listed in the documentation.

### Solution

Semantic tokens should be favored over Primitive tokens. This would also match their order in Figma.

### References

.

**Comment by lafray** [comment]
helping some people who were starting with shoreline. I saw a lot of people using primitive tokens because they didn't even realize that there were semantics. I think it's important to change this as soon as possible.

**Comment by davicostalf** [comment]
@lucasaarcoverde can you take this one? the doc generator needs to be updated

**Comment by lafray** [comment]
@davicostalf in Design Tokes we use `Bases` and in Color we use the term `Primitives`, which one is the correct?

**Comment by davicostalf** [comment]
@lafray We have Primitive Colors and Semantic Colors. We are no longer using Base for this.
