### ISSUE TITLE
Bulk action bar for Collection

### ISSUE THREAD

**Issue by malu-viana** [vtex/shoreline#1766]
### Problem

No momento temos o componente de Table no Shoreline e, apesar de já ter a variação de linhas selecionáveis, ainda não temos o componente para habilitar as ações em massa. Temos em diversos produtos (Logistics, Marketplace In/Out e Identity mapeados até então) a necessidade de aplicar ações em massa, atualmente utilizando a Table do Admin UI, que possui este componente.

Entendendo que existem casos de uso para este componente em múltiplos times, um desafio também é resolver os problemas de usabilidade contidos no componente do Admin UI, como:
- Conflito em casos de mais de uma table na tela
- Baixo contraste, o que levava a casos do usuário não perceber as ações
- Impossibilidade de aplicação nested em componentes como Modal e Sheet

### Solution
- A partir da seleção de algum item na listagem, a primeira coluna do `TableHeader` seria substituída pelo componente de `BulkActions`
- O componente de `BulkActions` consiste em: `MenuButton` + `Button`
- O CTA `Selecionar todos` seleciona todos os itens da listagem, não só da página (opcional o uso no design)
- Os feedbacks das ações executadas por este meio seguiriam o mesmo padrão da single action definida no design do produto

[Branch do componente no Figma](https://www.figma.com/design/Wk6xYuhi0HSnyNztyA3UQ2/Add-%5BBulk-action-bar%5D?node-id=5627-52187&t=uW58hvy2JFTvYJnF-4)

### Usage examples

![137](https://github.com/user-attachments/assets/7f8ed505-3a7f-4e2d-8199-f89fb7e6d247)
![125](https://github.com/user-attachments/assets/13f7dee9-3be5-4849-bd38-3475a87c76ff)
![128](https://github.com/user-attachments/assets/4e4be0aa-65f1-4e1b-8fb8-8ef12216e4cf)
![135](https://github.com/user-attachments/assets/508a461a-57ec-4dc7-97a5-392f385bc5dd)

### References

**Principais referências**
- [Vendure](https://docs.vendure.io/guides/extending-the-admin-ui/bulk-actions/)
- Notion
- Gmail
- Dropbox
- ICloud

**Outras referências**
| Ref 01 | Ref 02 | Ref 03 |
| --- | --- | --- |
| ![image 6](https://github.com/user-attachments/assets/d2422a6b-419a-4c80-803b-8c7e46d65268) | ![image 5](https://github.com/user-attachments/assets/12d75bc9-dac6-4cb1-aafa-2c2eda1e50b0) | ![image 1](https://github.com/user-attachments/assets/b8fce835-a658-49e5-a274-4bc56833b47e) |

**Comment by renatamottam** [comment]
Legal, Malu! Fiquei com algumas dúvidas:

1. O que teria que se criar de fato? Pelo que entendi, seria:
   - um botão de `bulk actions` dentro da `TableHeader` que apareceria quando algo fosse selecionado
   - alerta de erro/sucesso após ação (imagino que usaríamos uma `Toast` mas seria bom registrar isso pra engenharia)
2. Como ficaria a lista com nada selecionado? Esse botão vai de fato só aparecer quando você seleciona algo?
3. Não entendi porque tem o "Selecionar todos" e o checkbox que faz isso. Precisa dos dois?

**Comment by elleenvs-d** [comment]
Muito bom Malu ✨

**Comment by malu-viana** [comment]
@renatamottam 
1. Sim para o primeiro ponto. E os feedbacks das ações executadas por este meio seguiriam o mesmo padrão da single action definida no design do produto (toast é o padrão)
2. Isso! A partir da seleção de algum item na listagem, a primeira coluna do `TableHeader` seria substituída pelo componente de `BulkActions`
3. O CTA `Selecionar todos` seleciona todos os itens da listagem, não só da página (opcional o uso no design)

**Comment by lafray** [comment]
Eu tenho alguns pontos que acho que podem contribuir para a discussão.

1. A substituição parcial do header não pode virar um problema? No exemplo que você trouxe as imagens, o width da primeira coluna (sem contar a coluna de seleção) é grande, mas esse é sempre o caso? Por que se formos lidar com cenários em que essa coluna tem um width menor, podemos ter um problema de falta de espaço ou sobreposição de elementos. Vejo que em mobile talvez seja um problema tambem pela mesa questão. 

2. Sobre o label do selecionar todos, acho que seria importante ser mais explicito que é de todas as paginas. Pela minha experiencia com o bulkaction do Admin-ui, esse label já causava mals entendidos sobre o que é "todos". Talvez "Selecionar todas as paginas" ou "Selecionar em todas as paginas" 

3. Esse ponto é um pouco mais filosofico, mas acho que pode ser relavante. Estava olhando as referências que trouxe, e fi que uma delas não subistitui o header masi sim colocar uma "linha" a cima (ref 1). Ai fiquei pensando se esse caminho não seria mais interessante por ser mais fácil de lidar com o pontos que trouxe em "1". E pensando nisso olhei a referencia 2, em que não é nem em uma tabela exatamente, e sim uma listagem (pelo que entendi do recorte da imagem). E me perguntei que se formos nesse caminho de não ser o header, mas sim uma "linha a cima", não resolveriamos mais cenários mantendo uma consistencia de design?

4. Queria entender também a motivação da contagem ficar no label do botão.  Acho que essa escolhar pode trazer algums problemas:
  - Se formos por algo assim, acho que a definição do label acabaria ficando a cargo de quem usa, pois podem ter casos em que a ação não seja de edição, por exemplo. E dai mostrar a contagem também ficaria a cargo do usuário do componente. Vejo que rápidamente teram pessoas mostrando essa contagem de formas diferentes, e perderiamos em consistencia do design em diferentes apps. 
  - Semanticamente me parece estranho juntar num único elemento "o que"(ação) com "no que" (sob o que se aplica a ação). Normalmente quando precisamos dessas duas informações elas vem e elementos diferentes. Veja um modal de confirmação por exemplo, seu botão tem o label "confirmar" e não "confirmar item A" e o item ta em outro elemento, o titulo do modal, por exemplo.
  - Talvez seja só uma sensação minha. Mas me parece muito estranho um botão que o label fica mudando conforme vou selecionado e deselecionando elementos.

**Comment by malu-viana** [comment]
@lafray 

1. Todos os casos de uso de bulk action que analisei possuem um width da primeira coluna maior do que a barra para ações em massa seria. Acredito que para esse edge case, dessa largura da primeira coluna ser menor, podemos ir pelo caminho de setar uma min-width nos casos de ativas bulk actions na table.

2. Concordo com esse ponto. Pensei como reforço para a seleção da lista completa dois caminhos: Usar o contador de itens total (Selecionar todos X) ou mudar esse copy (Selecionar toda lista)

3. Esse caminho foi explorado, mas causa um layout shift na listagem pela adição do componente. E como a substituição deste no header é somente da primeira coluna, que por ser a principal informação da tabela não apresenta um problema o título ser ocultado momentaneamente, acabei entendendo que o ganho aqui seria maior.

4. Acho que a label deste botão deve ser fixa, o que seria editável seriam as ações no dropdown (quanto ao "editar", podemos estressar esse copy também pra deixar mais claro que são ações sob aqueles itens selecionados, ou alinhar que o editar faz sentido para contemplar quaisquer ações). Quanto ao botão com cotador e a ação indicar isso, é uma prática bem comum mesmo que não tenhamos casos de uso na VTEX seguindo esse padrão. Acho que quanto ao copy disso, vale o input de Localization também pra chegar nessa conclusão, principalmente no CTA de menu.

**Comment by dinizo-v2** [comment]
<img width="1133" alt="Screenshot 2024-07-30 at 12 03 41" src="https://github.com/user-attachments/assets/09efca6c-eff6-44ca-9de1-3abca253a5e1">

Um exemplo que gosto bastante de diferenciação de selecionar todos é do gmail.

**Comment by malu-viana** [comment]
> <img alt="Screenshot 2024-07-30 at 12 03 41" width="1133" src="https://private-user-images.githubusercontent.com/177033402/353511721-09efca6c-eff6-44ca-9de1-3abca253a5e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTIyNTIsIm5iZiI6MTcyMjM1MTk1MiwicGF0aCI6Ii8xNzcwMzM0MDIvMzUzNTExNzIxLTA5ZWZjYTZjLWVmZjYtNDRjYS05ZGUxLTNhYmNhMjUzYTVlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQxNTA1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmUyNGIzYzY2MjUxNzdkMmFjZDFlNzc5YmRhMDNiODQyNGNjYjg0Y2IwN2MyN2Y0YmM1ODY0N2IwZDdjZDA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qOmc7rXbT6VS3NTQNC3GUZaMYOx7ZT1reVmv2U6zYJc">
> Um exemplo que gosto bastante de diferenciação de selecionar todos é do gmail.

Também gosto bastante! Acho que um ponto nesse caso do Gmail é o uso do espaço com o copy né... Será que seguindo com a adição do contador já seria suficiente? "Select all 497" ou "Select all 497 items". Outro comportamento que gosto é de aparecer o "Select all" somente quando toda a página já está selecionada.

**Comment by lafray** [comment]
Uma pergunta sobre o comportamento do selecionar todos. Como fica a interação se depois dele clicar em selecionar tudo ele interagir com os seletores das linha, deselecionando itens?

**Comment by malu-viana** [comment]
@lafray Acho este um ótimo ponto pra ter a perspectiva de engenharia, por questões técnicas tb! No gmail por exemplo, caso a lista completa esteja selecionada e um item na página for selecionado, volta a se tratar da seleção na página

**Comment by davicostalf** [comment]
@malu-viana Esse ícone de três pontinhos no Menu o padrão é só usar ele quando o label é "More actions". O componente de Menu no Figma tem uma prop type, e nesse caso acho que o valor dela deveria ser "custom label".

---

> Outro comportamento que gosto é de aparecer o "Select all" somente quando toda a página já está selecionada.

Achei interessante isso também. Pode ser uma boa. Testaria como label "Select all pages"

---

> Como fica a interação se depois dele clicar em selecionar tudo ele interagir com os seletores das linha, deselecionando itens?

Temos até um comentário na documentação do Bulk Actions no Admin UI sobre esse cenário. Tem muito a ver com limitações de API. Acho que o componente dessa vez deveria ser desenvolvido considerando os dois cenários:

> What should happen when the Select All button is clicked?
> When the Select All action is triggered, all the items of all pages are selected.
> After the selection, the possibility of unselecting specific items depends on the API of the involved system. The ideal behavior is that the merchant can click on the Checkbox of specific selected items to unselect them.
> However, the API might not support registering all the items. In this case, when clicking Select All, the Checkbox of all items must be selected and disabled. It should only be enabled when the merchant clicks Deselect All.

---

@matheusps Fiquei curioso pra escutar sua opinião, considerando que você tinha muitas críticas sobre o componente anterior.

**Comment by beatrizmilhomem** [comment]
* Dúvidas: hoje só temos caso de ações em massa em lista? Deveríamos criar um componente agnóstico, que pode eventualmente funcionar em outros cenários? Até mesmo pensando num futuro que a gente tenha a opção de visualizar em grid ao invés de lista, esse posicionamento no header não funcionaria.

* Usaria o `Menu` em `tertiary`. Já pode existir outra ação primária na página.

* A referência das notificações do GitHub é interessante também. Uma outra coisa que essas refs tem em comum é a mudança na cor do fundo que vai ajudar a chamar atenção pra esse comportamento. Acho que é um teste válido tb! Eu lembro que Amanda ia fazer um teste mudando a cor de fundo do componente antigo, dá pra ver com ela o que que resultou esse teste.

<img width="1252" alt="image" src="https://github.com/user-attachments/assets/4e856315-5935-4d86-852e-f3ec1bc746b2">

**Comment by malu-viana** [comment]
@beatrizmilhomem Gosto dessa referência do Github também! Tá bem alinhada com a proposta. Sobre os dois primeiros pontos: concordo! Me diz o que tu acha dessa iteração?

![Group Management](https://github.com/user-attachments/assets/372f4d4c-f5c6-4404-8b76-d442c06535cb)

![Page](https://github.com/user-attachments/assets/73e1bc97-a791-4e98-a10c-7fba120c5dd6)

**Comment by matheusps** [comment]
A minha primeira reação à essa interação está no ponto 1 do @lafray:

> A substituição parcial do header não pode virar um problema? No exemplo que você trouxe as imagens, o width da primeira coluna (sem contar a coluna de seleção) é grande, mas esse é sempre o caso? Por que se formos lidar com cenários em que essa coluna tem um width menor, podemos ter um problema de falta de espaço ou sobreposição de elementos. Vejo que em mobile talvez seja um problema tambem pela mesa questão.

Acredito que o header deveria ser substituído pro completo para resolver essa provável inconsistência. Isso também deixaria mais espaço para novas ações importantes que não estivessem contidas em um menu, como acontece no Gmail. E sobre essa resposta:

> Todos os casos de uso de bulk action que analisei possuem um width da primeira coluna maior do que a barra para ações em massa seria...

Acho que temos pouco material dado a jovem idade do design system. Acho que uma substituição completa seria mais robusta para o futuro. 

Sobre a resposta do ponto 3. 

> Esse caminho foi explorado, mas causa um layout shift na listagem pela adição do componente

Não causaria um layout shift se juntássemos o conceito de filtragem bulk actions em uma mesma barra, como no Gmail. Claro, isso envolveria um redesign de como vemos filtros - mas é uma interação possível sem um shift. 

--- 

Completando, gosto do caminho - eu apenas faria uma substituição completa no header, ao invés de uma parcial.

**Comment by beatrizmilhomem** [comment]
> Me diz o que tu acha dessa iteração?

@malu-viana Tá ficando ótimo! ✨ Como ficaria no scroll com o header fixo? Outra coisa, chegou a testar sem o stroke no topo e laterais? Se quiser, compartilha o link onde vc tá fazendo as explorações tb. :)

> Completando, gosto do caminho - eu apenas faria uma substituição completa no header, ao invés de uma parcial.

Concordo com @matheusps , até olhando pra essa última iteração, manter as labels ali da direita fica até meio confuso. Substituindo todo o header vai acabar dando mais clareza pro comportamento de bulk actions, dá mais espaço pra possíveis outras ações e fica mais escalável pra telas menores.

**Comment by malu-viana** [comment]
@beatrizmilhomem @matheusps 

Substituir o header da Table me preocupa pelo usuário perder a referência das informações abaixo. Vamos imaginar num cenário onde existem múltiplas colunas retratando números, sem o header da Table essa falta de referência pode gerar um problema. No caso do Gmail funciona muito bem pois o header da lista já é o local de ações por default. 

Um caminho que pode funcionar, para nem perder a referência das colunas e nem ter essa quebra, é termos uma barra de ações fixa no caso de ações em massa estar ativa no componente de Table.

![Page](https://github.com/user-attachments/assets/700a5f4c-51c3-4e9c-9334-9e597949d49f)
![Page-1](https://github.com/user-attachments/assets/ff224bb1-f21a-4a5d-a130-d29e3c4c8132)
![Page-2](https://github.com/user-attachments/assets/2f5115cf-dc49-4eb7-95b3-702791c64673)

**Comment by matheusps** [comment]
Esse tá bem melhor @malu-viana

**Comment by BeatrizAlbino** [comment]
Esse componente é uma necessidade em Payments também! No passado eu precisei fazer uma migração de tela de listagem para o Admin UI e usei uma bulk actions bar para fazer inativação de regras em massa, mas a tela não foi implementada. Lembro que usei de referência o do Google Drive na época, hoje em dia ele mudou mas continuo achando legal a barra de cima, só acho pouco intuitivo a seleção de múltiplos itens sem checkbox.

Google Drive (atualmente):
<img width="1009" alt="image" src="https://github.com/user-attachments/assets/18d4bbd6-a005-41ef-b3c7-05795be6bdb9">

Projeto de Payment Rules (2021):
![image](https://github.com/user-attachments/assets/5c200adf-83b3-4041-ba61-49e56568c041)

**Comment by malu-viana** [comment]
Eu gosto muito desse bench do Notion com a floating bar! Acho que contempla os requisitos que trouxemos aqui na discussão: 
- Não sobrescrever outros componentes
- Não ocultar nenhuma informação existente
- Se manter nos limites da tabela, permitindo uso em cenários como: múltiplas tabelas na mesma página, nested em modal ou sheet
- Não pesar na UI em estado default

@beatrizmilhomem @matheusps @lafray @davicostalf o que acham desse caminho?

<img width="1440" alt="Page" src="https://github.com/user-attachments/assets/5dab3c1f-01e8-4b3f-876a-110290a51a65">
<img width="1440" alt="Page-2" src="https://github.com/user-attachments/assets/cf3e9efa-831f-4614-8d29-1158e1fbcfd5">
<img width="1440" alt="Page-1" src="https://github.com/user-attachments/assets/2da71750-6653-4d61-9694-8042b9c185b3">
<img width="1440" alt="Page-4" src="https://github.com/user-attachments/assets/5f56c12c-815a-4739-9cfa-c2310db4c85d">
<img width="1440" alt="Page-3" src="https://github.com/user-attachments/assets/2e88f238-6808-45aa-88b4-7acd14fab32f">

**Comment by lafray** [comment]
Eu particularmente achava mais interessante a interação anterior com a linha fixa. Tenho algumas inquietudes com esse camanhi da barra flutuante.

> * Não sobrescrever outros componentes
> * Não ocultar nenhuma informação existente
> * Se manter nos limites da tabela, permitindo uso em cenários como: múltiplas tabelas na mesma página, nested em modal ou sheet
> * Não pesar na UI em estado default
> 
> @beatrizmilhomem @matheusps @lafray @davicostalf o que acham desse caminho?
> 
> <img alt="Page" width="1440" src="https://private-user-images.githubusercontent.com/90862160/355149015-5dab3c1f-01e8-4b3f-876a-110290a51a65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDkxMTIsIm5iZiI6MTcyMjk0ODgxMiwicGF0aCI6Ii85MDg2MjE2MC8zNTUxNDkwMTUtNWRhYjNjMWYtMDFlOC00YjNmLTg3NmEtMTEwMjkwYTUxYTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDEyNTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4MGI0ZmRkNGE4ZjAxOThlMWRjMTdlNmY3NGYwYjBlMDllZGFkZjMzNDM0ODEyYThhNGQwNTFmODFmNWYzNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iYnLcWFcmynRT8GWUvpERykdM2SUSTLgjxJfQJnuI_4"> <img alt="Page-2" width="1440" src="https://private-user-images.githubusercontent.com/90862160/355149030-cf3e9efa-831f-4614-8d29-1158e1fbcfd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDkxMTIsIm5iZiI6MTcyMjk0ODgxMiwicGF0aCI6Ii85MDg2MjE2MC8zNTUxNDkwMzAtY2YzZTllZmEtODMxZi00NjE0LThkMjktMTE1OGUxZmJjZmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDEyNTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxZTY1NjgzYmM2NzQ5YjRkODJjMDcwZTExNmVmZTI1ODBhMTk2MDU4NTYxYjMzOGUyMDkwYzVkNGVlM2JkNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZzjfZfInbewJ7NIlQm-pBTmiL7BcI_s6X0gl99bge98"> <img alt="Page-1" width="1440" src="https://private-user-images.githubusercontent.com/90862160/355149032-2da71750-6653-4d61-9694-8042b9c185b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDkxMTIsIm5iZiI6MTcyMjk0ODgxMiwicGF0aCI6Ii85MDg2MjE2MC8zNTUxNDkwMzItMmRhNzE3NTAtNjY1My00ZDYxLTk2OTQtODA0MmI5YzE4NWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDEyNTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzYzU0NDVmYTJlYjkwMGMzZjViNWM1ZGFlNTljZjM0Yzc1Mjk3OTUxMWI4ODdkNjM2NDBhMzk2ODYwNWE5MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EhlsrsTU1o68pZWaP0Nsh9uElzRpCPJb1OgXZeh-edQ"> <img alt="Page-4" width="1440" src="https://private-user-images.githubusercontent.com/90862160/355149022-5f56c12c-815a-4739-9cfa-c2310db4c85d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDkxMTIsIm5iZiI6MTcyMjk0ODgxMiwicGF0aCI6Ii85MDg2MjE2MC8zNTUxNDkwMjItNWY1NmMxMmMtODE1YS00NzM5LTljZmEtYzIzMTBkYjRjODVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDEyNTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ODI3M2IwNjM3OWFjYTBkYjA4ZWM0YTRjYzZjZjY0ODdjYTQxN2U0OTNmMDBmMjAxYzYxYzRmYzczYTVhOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qegjym5hig1-P-C9tIjVfAeWifY3rWpB3XeLOBbZcSQ"> <img alt="Page3" width="1440" src="https://private-user-images.githubusercontent.com/90862160/355219516-417a4b16-0fc1-4e96-9a06-c2f2a1578e97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDkxMTIsIm5iZiI6MTcyMjk0ODgxMiwicGF0aCI6Ii85MDg2MjE2MC8zNTUyMTk1MTYtNDE3YTRiMTYtMGZjMS00ZTk2LTlhMDYtYzJmMmExNTc4ZTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDEyNTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmOTM2NjQ2MDZlNzFjYmFjZjJmMjA0ZTYxNzBkODYyNDQ5NGI4NWE1Nzk1YzgzY2FmYjVjMzI2N2M0NDVhYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qYKeWQfru7N_oa8B_FmQpdxH3BhtEQ_vB3zecYh9LMQ"> <img alt="Page5" width="1440" src="https://private-user-images.githubusercontent.com/90862160/355219523-501a7718-2a3b-464d-b8c0-8ad5bb2aa8e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDkxMTIsIm5iZiI6MTcyMjk0ODgxMiwicGF0aCI6Ii85MDg2MjE2MC8zNTUyMTk1MjMtNTAxYTc3MTgtMmEzYi00NjRkLWI4YzAtOGFkNWJiMmFhOGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDEyNTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MzA0OTQxYTIxOWQxODcwNWI4Y2MxZTM5MjQ5MGUwNTBhNmUzMzJkOTNhMjU3NGVmNDIxMmRmMTU2OTJjOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l7i5-D67hLwnOBbt6eToOapijuM2X-cQ1kwr6i1CmXg">

**Comment by lafray** [comment]
Eu particularmente achava mais interessante a interação anterior com a linha fixa. Tenho algumas inquietudes com esse camanhi da barra flutuante.

> * Não ocultar nenhuma informação existente
 Não oculta permanentemente, mas o usuário tem que ficar trocando ela de lugar para conseguir enxergar o que esta embaixo. Eu costumo odiar telas com esse tipo de interação quando.

Mas o ponto que mais me preocupa é acessibilidade. 
A navegação por teclado fica prejudicada. Você não consegue fazer uma navegação por teclado intuitiva para mudar o componente de lugar para enxergar o que esta embaixo. O usuário tera que ficar recorrendo ao mouse para mudar a posição do elemento.
Leitor de tela não sei se não fica prejudicado também

**Comment by davicostalf** [comment]
Já passamos por algumas soluções:
1. Barra flutuante fixa (como era no Admin UI)
2. Barra flutuante reposicionável
3. Menu com ações substituindo label da primeira coluna da tabela
4. Barra que substitui header da tabela e esconde o label de todas as colunas
5. Barra entre os filtros e o table header, visível até quando não há seleção
6. Barra entre os filtros e o table header, que aparece após seleção

Todas as opções tem seus prós e contras. Até agora minhas favoritas são a 3 e a 6. Tem também outra opção que eu acho interessante, que é mostrar as ações contextuais no lugar onde já ficam normalmente as ações no Collection:
![image](https://github.com/user-attachments/assets/0b49d5bf-3011-4e78-afd6-a620a15f5035)

**Comment by matheusps** [comment]
Para mim, a opção 4 é a melhor pois é intuitiva em termos de UX, escalável em diferentes tamanhos de tela e tabela, e tem uma implementação pouco problemática.

**Comment by BeatrizAlbino** [comment]
Gostei bastante da 6! Não esconde as labels das colunas e também não fica fixo na UI default

**Comment by malu-viana** [comment]
@matheusps @BeatrizAlbino @davicostalf @renatamottam @beatrizmilhomem @lafray 

Obrigada por todos os pontos! Acho que os tradeoffs de cada caminho já estão bem delineados. Com tudo que foi dito, a opção 6 carrega o menor dos problemas levantados: o layout shift. Acho que o próximo passo agora é alinhar a interação no momento de seleção do primeiro item, para tentar mitigar esse problema. 

Quanto a opção 2, levantada por @matheusps, ocultar o header da tabela vai contra algumas heurísticas de usabilidade, podendo trazer um sério problema de UX pro usuário, nos casos de uma listagem mais complexa (múltiplas colunas exibindo dados numéricos, por exemplo), ao perder a referência do que seriam os valores listados.

Gravei um vídeo da opção 6 iterada, vejo como uma opção escalável, com affordance pro usuário e sem conflitos de acessibilidade e responsividade de tela.

https://github.com/user-attachments/assets/6c3733a0-0ffd-42a6-913d-652824b62460

@davicostalf Explorei bastante o caminho das ações ao lado da paginação, é uma opção bem interessante também, mas vejo sendo menos escalável por questões de hierarquia e espaço. Posso te mostrar o que explorei se quiser :)

**Comment by matheusps** [comment]
@malu-viana, meu principal problema com essa solução é o [Layout Shift](https://web.dev/articles/cls). Inclusive, esse problema já foi apontado na tabela que tínhamos no [Styleguide](https://styleguide.vtex.com/#/Components/Display/Table).

**Comment by lafray** [comment]
@malu-viana e @matheusps, você acreditão que o espaço que a solução 5 ocupa é tão grave assim? Pq é a solução que resolver os dois prinicipais pontos de preocupação de vcs. Não tem layout shift nem oculta informação. Se tiverem soluções inteligentes para mobile para evitar que os elementos firem multiplas linhas, o espaço vertical ocupado não vejo como critico. Não crítico ao ponto de valer a pena essas outras duas perdar.

**Comment by matheusps** [comment]
@lafray, acho que 5 e 6 tem o mesmo problema: As ações ficam quebradas em dois espaços, sendo eles:

1. O checkbox no header da table, que tem a ação de selecionar todos
2. A barra do header. 

O gmail resolveu esse problema juntando o checkbox com essas ações:

<img width="533" alt="Screenshot 2024-08-08 at 15 17 22" src="https://github.com/user-attachments/assets/322a55f4-cd10-4d3e-865a-8f62d2d1da41">

**Comment by beatrizmilhomem** [comment]
Oi pessoal! @malu-viana , conversamos agora durante o office hours, junto com @lafray , e pensamos em uma sugestão sobre como seguir agora: vcs decidem dentro do time qual o melhor caminho pro contexto atual (se o 5 ou o 6) e implementam o componente no time de vcs por enquanto, sem adicionar ainda à biblioteca.

Por que essa sugestão? Estamos num impasse em que nenhuma solução ainda parece a ideal, por isso está tão difícil chegar em um acordo. Entendemos que o problema maior pode estar, na verdade, no header do Collection. A ideia agora é discutir a revisão desse ponto, podemos começar por aqui https://github.com/vtex/shoreline/issues/1811.

Malu e Lais ficam ok de seguir assim?

**Comment by malu-viana** [comment]
Faz sentido para mim @beatrizmilhomem  :)

**Comment by lafray** [comment]
As we had discussed, I created it in our only monorepo. It was created through this [PR](https://github.com/vtex/admin-mercadolivre-monorepo/pull/36). I'm sharing it here because I thought you might be interested in taking a look (there's a lot of room for improvement since we had a significant time constraint). You can see how it's using the project's storybook (`pnpm run docs`). After you guys advance in defining the designer, who knows, maybe I'll help you create the version here for the shoreline.

**Comment by beatrizmilhomem** [comment]
Como essa discussão já foi concluída, vou fechar essa issue. Depois que o header do Collection for resolvido em https://github.com/vtex/shoreline/issues/1811 , uma nova issue pode ser criada com a nova proposta.
