### ISSUE TITLE
Pagination: Figma component props don't support single page scenario

### ISSUE THREAD

**Issue by davicostalf** [vtex/shoreline#1767]
### Problem
A range needs to be specified

<img width="678" alt="Captura de Tela 2024-07-29 às 17 22 25" src="https://github.com/user-attachments/assets/d6be9c7b-2fbb-4b6a-8c65-c1625ab239c1">

### Expected behavior
There should be a variant for this, layers shouldn't need to be manually hidden.

**Comment by renatamottam** [comment]
Agreed!
Would also be nice to change `next` and `previous` variants to a toogle (using true/false as value).

**Comment by davicostalf** [comment]
I though about this as well, @renatamottam. I was unsure about this change since we plan boolean props so they are inactive by default, and in this scenario this would make the props strange. Something like previous and disableNext. But in this case I think it's worth it to open an exception.

**Comment by beatrizmilhomem** [comment]
Why do you think that showing `1 – 3 of 3` doesn't work?

**Comment by davicostalf** [comment]
It seems unnecessary to me. And I don't think the complexity added to the component is a problem, since it's a very simple component.

**Comment by beatrizmilhomem** [comment]
Next step: make the fix proposal.

**Comment by davicostalf** [comment]
Fixed in the last update to the Figma library.
