### ISSUE TITLE
Fix: `TabList` component on Figma

### ISSUE THREAD

**Issue by renatamottam** [vtex/shoreline#1772]
### Problem

Our current `TabList` component have 5 tab items, but the last two are not using the `TabList/⚙️Tab` component as base.

|TabList|Tab Item| Tab Item Error|
|-|-|-|
|<img width="131" alt="Screenshot 2024-07-30 at 12 00 20" src="https://github.com/user-attachments/assets/fa3b4a7e-c395-4e00-91e3-91dcfada1736">|<img width="264" alt="image" src="https://github.com/user-attachments/assets/fe931313-76b2-4253-8968-e630a137a002">|<img width="262" alt="Screenshot 2024-07-30 at 12 02 11" src="https://github.com/user-attachments/assets/703dc439-3331-477a-ade0-7b63dbe5afad">|

### Expected behavior

It should be possible to change Tab Items variants after selection.

|Expected behavior| Error (Last 2 items)|
|-|-|
|<img width="745" alt="image" src="https://github.com/user-attachments/assets/7add5767-9bcc-4c44-8014-7cd1528996af">|<img width="745" alt="image" src="https://github.com/user-attachments/assets/6ef00e8c-26da-43f5-9f20-b0d002c842bf">|

### Reproducible Example

[TabList component on Figma](https://www.figma.com/design/PWGSQ26U55u8E34JWn9ZYE/Shoreline-%E2%80%93-Components?node-id=1020-1892&t=kBkUEYP3aT3M0WEN-4)

### Suggested solution

Update `Tab 4` and `Tab 5` instances to `TabList/⚙️Tab`.

### Package

@vtex/shoreline

**Comment by beatrizmilhomem** [comment]
Fixed and published.
