### ISSUE TITLE
Select Popover items 6 and 7 missing icon on Figma

### ISSUE THREAD

**Issue by felipepowlist** [vtex/shoreline#1778]
### Problem

For some reason, items 6 and 7 in the Figma Componet are missing the icon. Because of that, when we add these items, they misalign. 

<img width="1248" alt="Captura de Tela 2024-07-31 às 17 24 13" src="https://github.com/user-attachments/assets/1f7178c3-381b-4566-a46b-7c113a2dc9b6">

### Suggested solution

I created a branch with a solution [here](https://www.figma.com/design/PWGSQ26U55u8E34JWn9ZYE/branch/M77UXgP4L6DuhOuYmOZNd4/Shoreline-%E2%80%93-Components?m=auto&node-id=1840-17704&t=9HLnWAg3jkcMETdm-1)

### Package Manager

pnpm

**Comment by beatrizmilhomem** [comment]
Great! ✨ Everything looks right, I'm merging the branch.
