### ISSUE TITLE
Write the Best Practices documentation for the component Drawer

### ISSUE THREAD

**Issue by beatrizmilhomem** [vtex/shoreline#1783]
Write the Best Practices documentation for the component Drawer.
* [Figma](https://www.figma.com/design/PWGSQ26U55u8E34JWn9ZYE/Shoreline-%E2%80%93-Components?node-id=5744-31605&t=mMAHDdjCKsTkqQwQ-4).
* [Component specs](https://www.figma.com/design/NmC9IaAfxgh4amOtYJMiWw/Drawer-Handoff?node-id=0-1&t=mUmgVxG9y0rLtQDU-1).

**Comment by beatrizmilhomem** [comment]
[Proposta de documentação](https://docs.google.com/document/d/19ycJPf06u0-lNpeYWqtXAWU2ypNxPInc_K2uddXBqjY/edit?usp=sharing)

**Comment by davicostalf** [comment]
Li a documentação mas ainda não está claro pra mim quando um modal deveria ser usado e quando uma drawer deveria ser usada.

**Comment by beatrizmilhomem** [comment]
@davicostalf pra mim, a diferença tá em:
- Modal é pra casos em que precisa de toda a atenção do usuário, por isso interrompe o fluxo e não permite interação com o conteúdo embaixo. Por ex, confirmar uma ação, concordar com termos e condições, preencher dados que podem ter um impacto imediato.
- Drawer como tá na proposta: Drawers allow users to interact with content outside the overlay. Include in a Drawer content that is related to a minor job within the main job of a Page that doesn't demand complete attention and block the user flow. For example, minor jobs can be filling out a small form before performing an action (e.g. to edit SKU metadata) or viewing additional information (e.g. details of a security finding).

**Comment by davicostalf** [comment]
Boa!
