### ISSUE TITLE
Small size for buttons

### ISSUE THREAD

**Issue by felipepowlist** [vtex/shoreline#1785]
### Summary

The Content Platform's UI needs to be scalable since we don't control how the forms are structured. Because of that, we have been working with a more compact UI framework for it. During the design phase, we missed having a smaller button for specific interactions. We tried using our current regular size, but it made the interface increase exponentially, and considering how these interfaces can grow, every pixel counts here. Another consideration is that these are mainly Desktop focused interfaces. We should consider adapting button sizes for mobile, when we design these use cases. 

 The idea is that we could just scale down the button to be 28px to fit these compact use cases. (we are also testing it with the default foreground color being the soft and not the secondary) 

Here are some of some of the use cases we will need to implement now : 

**Side bar actions**
<img width="1576" alt="Captura de Tela 2024-08-01 às 11 22 41" src="https://github.com/user-attachments/assets/509cd8bd-2eb9-4b88-84e8-f195c182192e">

**Field actions** (we only have one now, but it will scale)
<img width="2229" alt="Captura de Tela 2024-08-01 às 11 26 29" src="https://github.com/user-attachments/assets/57e0d5f9-c238-4e7c-a1c2-0ba4edcf7c5d">

<img width="1747" alt="Captura de Tela 2024-08-01 às 11 36 37" src="https://github.com/user-attachments/assets/c411b8c9-6502-4a17-8c66-c553130f50ef">

### Benchmarks
Good **benchmarks** are these buttons here in **GitHub**, as well as most of the buttons on **Figma's** and **Shopify's** buttons
<img width="1441" alt="Captura de Tela 2024-08-01 às 11 43 02" src="https://github.com/user-attachments/assets/35ff1f6c-e103-41f1-b51d-b453c9c73be4">

<img width="1173" alt="Captura de Tela 2024-08-01 às 11 43 25" src="https://github.com/user-attachments/assets/a5a91542-d1f5-40c6-8e6f-47eb0f129fc3">

<img width="1262" alt="Captura de Tela 2024-08-01 às 11 46 19" src="https://github.com/user-attachments/assets/552bb8fc-5f1e-4783-88de-f3f989a34a8e">

**Comment by matheusps** [comment]
Although this is concerning for mobile (should be at least 44px, i guess), it makes sense for desktop. @felipepowlist, the font-size remains the same of the "normal" button, right?

**Comment by felipepowlist** [comment]
Yes, my proposal is to keep everything the same and just adjust the size. And I'd propose to only use this size on desktop. @matheusps

**Comment by davicostalf** [comment]
@felipepowlist I think that it would be worth it to include a complete screen with the smaller button that currently exists and the proposed button. So we can get a sense of overall dimensions and how this new button relates with current elements.

**Comment by felipepowlist** [comment]
Here's a [prototype](https://www.figma.com/proto/fK2y0eEfHbV3iC6KeMqYYf/MVP-prototypes?page-id=4747%3A27050&node-id=4747-43670&viewport=390%2C1051%2C0.06&t=7eVTKED2SZOfOqo4-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=4747%3A43670&show-proto-sidebar=1) with the buttons in I showed in the screenshots

@davicostalf

**Comment by davicostalf** [comment]
Browsing the prototype I noticed there are no large buttons in the page, not even in the page header. It seems to me that this page is in a different density then the rest of the Admin, as can be noticed by the height of the page header. What pages do you think we should design in this density, as opposed to the current Admin density?

I also observed two use cases for this small button: inline with text and inside inputs. Comparing to a normal-sized button inside an input, I still believe that a normal-sized button is more appropriate for this use case. When it comes to actions inline with text, that's where I feel that we have an opportunity. The tertiary button even with bleed applied would look strange in these scenarios.

**Comment by beatrizmilhomem** [comment]
We agreed with @felipepowlist that he'll move on by applying the small button in his context to test and validate, for now.
