### ISSUE TITLE
Input behavior

### ISSUE THREAD

**Issue by lafray** [vtex/shoreline#1786]
### Problem

As can be seen in the example given here, the shoreline input does not work correctly when its value is manipulated via reference, as is done by some form libs such as `react-hook-form`.

### Expected behavior

I expected the shoreline input to have the same behavior as a native input. That is, it could use the same form libs that are used with native inputs.

### Reproducible Example

[codesandbox](https://codesandbox.io/p/sandbox/shoreline-input-cts7fc?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxxp0vg700063b6ka2bsgc0k%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxxp0vg700023b6kmmpmzu99%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxxp0vg700033b6kxk0jsics%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxxp0vg700053b6ked2ynqg7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxxp0vg700023b6kmmpmzu99%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxxp0vg600013b6kq2ivj55n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzb8e1bp00023b6iihmy3l9r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A15%252C%2522startColumn%2522%253A79%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A79%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxxp0vg700023b6kmmpmzu99%2522%252C%2522activeTabId%2522%253A%2522clzb8e1bp00023b6iihmy3l9r%2522%257D%252C%2522clxxp0vg700053b6ked2ynqg7%2522%253A%257B%2522id%2522%253A%2522clxxp0vg700053b6ked2ynqg7%2522%252C%2522activeTabId%2522%253A%2522clxxp0vg700043b6k5l8f224p%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxxp0vg700043b6k5l8f224p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522isCloud%2522%253Afalse%252C%2522id%2522%253A%2522clxyp37ii001t3b6jzxcgzt2l%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clxxp0vg700033b6kxk0jsics%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxxp0vg700033b6kxk0jsics%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Suggested solution

I couldn't figure out just by looking at the code the motivation for adding the `useControlledState` hook. The problem is solved by removing it. Does this hook actually have any use that prevents it from being removed?

### Package

@vtex/shoreline

### Packages version

1.1.11

### Browser

chrome

### Package Manager

pnpm

**Comment by matheusps** [comment]
You can use the [Controller component](https://react-hook-form.com/docs/usecontroller/controller) from the react-hook-form to implement this behavior.

**Comment by lafray** [comment]
For the record, in case other people have problems. It actually works correctly with the `react-hook-form` Controller.
