### ISSUE TITLE
Field style

### ISSUE THREAD

**Issue by lafray** [vtex/shoreline#1787]
### Problem

When used, the field does not have the same behavior as the pure input of occupying the entire width of the parent. And even when used in a stack with fluid, the element does not occupy the entire width, forcing you to manually configure this.

### Expected behavior

I expected the style of occupying all the space to be the same as the pure input (without the field wrapper), or that at least when in a stack the fluid would have an effect.

### Reproducible Example

[codesandbox](https://codesandbox.io/p/sandbox/shoreline-field-dl4wf3?file=%2Fsrc%2FApp.tsx%3A15%2C13&workspaceId=d1c828d7-d04f-40e4-84be-d8c0f0390ada)

### Suggested solution

Remove this line: https://github.com/vtex/shoreline/blob/6d98d7bafa846c995571ea78282db23d7d38da2c/packages/shoreline/src/themes/sunrise/components/field.css#L4

Or add a style to field inside a stack with fluid to set width to `auto`

### Package

@vtex/shoreline

### Packages version

1.1.11

### Browser

chrome

### Package Manager

pnpm

**Comment by matheusps** [comment]
I'm good for changing the width to 'auto'
