### ISSUE TITLE
Image cell in Table should be an Image

### ISSUE THREAD

**Issue by davicostalf** [vtex/shoreline#1791]
### Problem

The image component currently features a placeholder image composed of a background color and an icon.
<img width="823" alt="image" src="https://github.com/user-attachments/assets/fea93cb2-f9e4-4fb6-85d9-407df1485aec">

### Expected behavior

The image component should be an actual image so it's easier to replace, such as by just copying and pasting an image in the image layer.

**Comment by matheusps** [comment]
@davicostalf should we have an image component on code?

**Comment by davicostalf** [comment]
@matheusps I thought we did. If not, I believe so.

**Comment by lafray** [comment]
I didn't quite understand. Is the idea to create a component with the background and the icon? Is this discussion mature enough to go to the backlog, in the sense that it has already been decided that this will actually be implemented?

**Comment by davicostalf** [comment]
I just updated the Image Placeholder component in Figma to be an actual image. 
@lafray I created a separate issue (#1922) where we can discuss if it makes to have an Image component in code and what it's API should be.
