### ISSUE TITLE
Vertical tabs component with data

### ISSUE THREAD

**Issue by BeatrizAlbino** [vtex/shoreline#1796]
### How can we help?

Estamos desenvolvendo um componente de funil + gráfico para uma dashboard que deve ser claramente identificável como clicável. Exploramos diversas opções de design e já realizamos testes de usabilidade. Após testes, um dos usuários mencionou que não estava intuitivo e os outros três demoraram a entender o clique (mas clicaram). 

Acreditamos que isso pode ocorrer porque, ao abrir a interface, o primeiro gráfico já está aberto, o que pode dar a impressão de que o componente é estático e depende da curiosidade do usuário para clicar no resto. Quero abrir uma discussão para explorar novas opções de design que possam melhorar a clareza de que o componente é clicável. Busco sugestões para aumentar a visibilidade e a intuitividade desse elemento para todos os usuários.

Existe algum padrão de design ou exemplo que poderia ser aplicado aqui?

Agradeço qualquer insight ou sugestão!

<img width="1207" alt="image" src="https://github.com/user-attachments/assets/5f111c91-b7c4-448c-a9eb-1ac93cbcc7bb">

<img width="1207" alt="image" src="https://github.com/user-attachments/assets/74c1a8c3-5cea-408b-97d9-bc8792e6fc49">

### What have you tried?

Algumas das alternativas já exploradas
<img width="849" alt="Captura de Tela 2024-08-02 às 12 50 26" src="https://github.com/user-attachments/assets/62e377e4-3033-46af-8c87-cf7c7df2ed93">
<img width="849" alt="Captura de Tela 2024-08-02 às 12 50 45" src="https://github.com/user-attachments/assets/254cc2b0-968d-451d-98aa-5f3903b71f5d">
<img width="849" alt="Captura de Tela 2024-08-02 às 12 50 55" src="https://github.com/user-attachments/assets/3782da62-020a-47f6-88ea-28a3974a3ae6">
<img width="849" alt="Captura de Tela 2024-08-02 às 12 51 09" src="https://github.com/user-attachments/assets/a6c0f534-e815-4649-8620-51715d703c0a">
<img width="929" alt="Captura de Tela 2024-08-02 às 12 51 37" src="https://github.com/user-attachments/assets/ad0facee-f44d-4b83-9dde-74fe6a3dd8ef">

### Additional information

[Figma com protótipo para testar](https://www.figma.com/proto/TGcMXqiZl74rtFxlccnHzk/Testes-MVP---Fraud-Control?page-id=1%3A17&node-id=23-22701&viewport=5654%2C5559%2C0.52&t=051tnBJxaEvq62Fg-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=23%3A22701&show-proto-sidebar=1)

**Comment by BeatrizAlbino** [comment]
(Não sei colocar label de design)

**Comment by matheusps** [comment]
Sobre a implementação desse padrão, recomendo o uso de tabs. https://www.w3.org/WAI/ARIA/apg/patterns/tabs/.

**Comment by BeatrizAlbino** [comment]
Fizemos com tabs também porém ela exige que o funil seja separado do gráfico, gerando clique repetido pra ver cada etapa do funil da esquerda

<img width="1207" alt="image" src="https://github.com/user-attachments/assets/0296736e-41d8-4a1d-9684-2d6c4e10f4d1">

**Comment by davicostalf** [comment]
Eu acho que a sugestão de Matheus era que por trás se usasse o padrão de Tabs do WAI-ARIA para implementar, mas não necessariamente o componente de Tabs do Shoreline. Entre os estudos que você compartilhou, essa daqui parece seguir uma linguagem visual parecida com o nosso componente de tabs atual, por tirar a saturação das tabs que não estão sendo visualizadas:
![image](https://github.com/user-attachments/assets/ceb2d560-7f79-4b1d-9f26-40e127617ad5)

Queria deixar aqui na thread um exemplo que já está implementado no Admin, na página de Sales Performance:
![storecomponents myvtex com_admin_sales-performance__viewId=6e0a40c4-546d-11ec-82ac-16e0966f28c9](https://github.com/user-attachments/assets/3f2b164f-49ed-4fc0-825f-714890f45d31)

Outro exemplo é um estudo que fiz para o produto de search:
![image](https://github.com/user-attachments/assets/d777cae2-22e5-47ae-a35f-fbce589f175f)

**Comment by matheusps** [comment]
Isso @davicostalf, mal a falta de clareza 😅

**Comment by beatrizmilhomem** [comment]
Já tentou fazer algo parecido com o do sales performance @BeatrizAlbino ? Que eu acho que nessa solução é onde tá melhor resolvida a conexão da informação com o gráfico. Talvez até testar algo nessa linha mas na disposição que vc tá usando mesmo (vertical).

**Comment by beatrizmilhomem** [comment]
Pensei em algo assim:

![image](https://github.com/user-attachments/assets/0f23390a-7d69-4b5f-b602-b87f530c5821)

![image](https://github.com/user-attachments/assets/e2b604dc-7209-41ff-999a-935e92d63f7a)

**Comment by beatrizmilhomem** [comment]
@BeatrizAlbino Conseguiu resolver? Ainda precisa de alguma ajuda?

**Comment by BeatrizAlbino** [comment]
Olá, achei que as soluções com as cores no cinza acaba parecendo que fica em estado de disabled e perde um pouco da visualização do funil. Decidi seguir com as cores no azul mesmo.
