### ISSUE TITLE
[Teste] Inclusão de novos ícones no Shoreline

### ISSUE THREAD

**Issue by nikolaspereira** [vtex/shoreline#1801]
### Problem

Recentemente senti a necessidade de utilizar ícones da biblioteca Phospor que ainda não possuímos no Shoreline.

### Solution

Incluir os ícones novos no Shoreline caso outras pessoas queiram utilizá-los.

### Usage examples

![Captura de Tela 2024-08-07 às 10 33 11](https://github.com/user-attachments/assets/29ba12ff-94e1-4d8e-8d45-9029a0ad232e)

### References

None

**Comment by beatrizmilhomem** [comment]
Tem o ícone x que eu tb acho que adicionar.

**Comment by beatrizmilhomem** [comment]
> Tem o ícone x que eu tb acho que adicionar.

hagdiaugidg

**Comment by beatrizmilhomem** [comment]
https://github.com/vtex/shoreline/issues/1802

**Comment by fernandacolodetti** [comment]
@nikolaspereira conversa com a Jack, Amandinha e Rhebs. Elas tem outros cenários!

**Comment by renatamottam** [comment]
@rhebeca
