### ISSUE TITLE
[teste] teste rhebs

### ISSUE THREAD

**Issue by rhebeca** [vtex/shoreline#1802]
### Summary

Encontrei problema x enquanto prototipava e acredito que tais soluções possam ajudar 

- [ ] prototipo 1 
- [ ] Prototipo 2 

### Rationale

teste

**Comment by nikolaspereira** [comment]
> teste comentário

This

**Comment by amandavcp** [comment]
> teste comentário

**Comment by biaoliveira28** [comment]
concordo e tenho esse caso aqui tmb

**Comment by gabriel-niemeyer** [comment]
**Lista de coisas para fazer**

- [ ] Coisa 1
- [ ] Coisa 2
- [ ] Coisa 3
