### ISSUE TITLE
[Teste] Cor de botão de erro está diferente no hover

### ISSUE THREAD

**Issue by JessieMeguro** [vtex/shoreline#1808]
### Problem

O botão de erro está com a cor `#FB12A0` no hover mas deveria ser `#FB120A`

### Expected behavior

Ao estar em hover, o botão deveria ficar acizentado (`#b1b1b1`) ao invés de vermelho.

### Package

@vtex/shoreline

> teste

- [x] teste
- [ ] teste

https://github.com/vtex/shoreline/issues/1807

**Comment by beatrizmilhomem** [comment]
Não concordo. Tinha a cor x

**Comment by pedroalexandria** [comment]
Testando aqui

**Comment by beatrizmilhomem** [comment]
Eu vou resolver
