### ISSUE TITLE
404 error when clicking on the 'Toast' component card

### ISSUE THREAD

**Issue by elleenvs-d** [vtex/shoreline#1809]
### Problem

I notice that this component car tab is giving 404 error when is clicked. 
<img width="411" alt="Captura de Tela 2024-08-07 às 16 07 04" src="https://github.com/user-attachments/assets/c9a09dd7-420f-47de-9f67-bf849629a76a"> 

When I click, the page does not load, and appears an 404 error. 
<img width="1099" alt="Captura de Tela 2024-08-07 às 16 07 30" src="https://github.com/user-attachments/assets/68bae2db-28a8-4679-b928-2ee86ccccb85">
Link: https://shoreline.vtex.com/components/toast-stack

### Expected behavior

I believe the card url is outdated and the expected one is: https://shoreline.vtex.com/components/toast that's why I can not navigate directly from the card.

### Package Manager

pnpm

**Comment by beatrizmilhomem** [comment]
Hello, Ellen! Thanks for reporting this bug. 😊 
There is another issue that already includes this broken link https://github.com/vtex/shoreline/issues/1598 and someone is already working on it, so it's expected to be fixed soon.

I'll close the issue since it is duplicated.
