### ISSUE TITLE
Hard to search for Tag in Figma

### ISSUE THREAD

**Issue by davicostalf** [vtex/shoreline#1838]
### Problem

There are two issues with the Tag component in Figma:
- The primary Tag is the default, instead of the secondary Tag
- The Tag Cell has the same component name as the Tag
<img width="297" alt="Captura de Tela 2024-08-19 às 12 00 38" src="https://github.com/user-attachments/assets/bb3ea079-04a9-4e07-8e9d-ac67bede73e6">

### Expected behavior

- Secondary tag should be the default
- Tag Cell should have a different name from Tag

**Comment by beatrizmilhomem** [comment]
> The Tag Cell has the same component name as the Tag

The same happens with Button and Checkbox.

**Comment by davicostalf** [comment]
Fixed in the last update to the Figma library.
