### ISSUE TITLE
Falta de z-index no Popover do Select

### ISSUE THREAD

**Issue by luarakerlen** [vtex/shoreline#1839]
### Problem

Eu acredito que falta ser adicionado um [z-index no popover do select](https://github.com/vtex/shoreline/blob/main/packages/shoreline/src/components/select/select-popover.tsx), pois atualmente ele fica por baixo de outros componentes, como o Radio Button, por exemplo, conforme a imagem:

![image (3)](https://github.com/user-attachments/assets/43e28f0a-fa21-467b-93bd-d84e25f89883)

### Package Manager

pnpm

**Comment by lucasaarcoverde** [comment]
@luarakerlen esse problema acontece com outro componente sobrepondo o Popover do Select? Caso seja apenas o Radio, talvez o problema seja no Radio e não no Select

**Comment by luarakerlen** [comment]
Não, @lucasaarcoverde. Pode ser então que o problema seja no Radio.

**Comment by lafray** [comment]
Checando aqui, o problema ocorre tambem no checkbox 
![image](https://github.com/user-attachments/assets/f0488efa-881f-4db3-874c-41dc5d4ce1a3)

**Comment by lafray** [comment]
Existia um problema no popove do select que já estou arrumando.
![image](https://github.com/user-attachments/assets/c2d31486-a102-451e-af5a-7ce9ae635f73)

Mas tambem existe um problema com o radio e checkbox. Pois eles tem um z index de alguma forma que passa por cima de alguns elementos como mostrei no header do modal

**Comment by lafray** [comment]
O porblema dele passar por cima vem da position relative
![image](https://github.com/user-attachments/assets/312da089-4876-4bad-84ea-d29bbb9ddc29)
![image](https://github.com/user-attachments/assets/32d31ac9-f1ce-4383-a797-b1dbef4a4b27)

Porem se só retirar o position, da problema na bolinha branda do input selecionado. Da para arrumar acho que adding uma div extra. Mas como é mais complexo vou separar em outra PR

**Comment by lafray** [comment]
> Porem se só retirar o position, da problema na bolinha branda do input selecionado. Da para arrumar acho que adding uma div extra. Mas como é mais complexo vou separar em outra PR

Acabei conseguindo arrumar de forma simples e pus na mesma pr porem em commit separado
