### ISSUE TITLE
Tab: fix label color in active state

### ISSUE THREAD

**Issue by felipepowlist** [vtex/shoreline#1849]
### Problem

The active state of the tab component in Figma is different from the one in code. In Figma the text turns blue and in Code it stays black.

**Figma**
<img width="1299" alt="Captura de Tela 2024-08-21 às 14 27 23" src="https://github.com/user-attachments/assets/3f4ace8b-41f1-4e21-9305-33df98eaf5cc">

**Code**
<img width="1229" alt="Captura de Tela 2024-08-21 às 14 27 47" src="https://github.com/user-attachments/assets/6ac5f42a-3a5b-42c7-9296-d48d3ba7b0ca">

### Suggested solution

Fix the label color in the code when the tab is active. It should be `fg-accent`.

**Comment by felipepowlist** [comment]
I suggested the fix here in this [branch](https://www.figma.com/design/zNrWJSP55F1rSYhfbqhan9/Fix-%5BTab%5D-to-match-code?node-id=1940-92442&t=ShyVvhIg4gnNnFju-4). Can somebody review?

@beatrizmilhomem @davicostalf

**Comment by beatrizmilhomem** [comment]
Actually, the bug is in the code. The active tab label should be `fg-accent`.
I'll change the title of the issue so a developer can act on it.
