### ISSUE TITLE
TextProps is not exported and can't be extended

### ISSUE THREAD

**Issue by vaporwavie** [vtex/shoreline#1852]
### Problem

While trying to compose a custom handler around the `Text` component, I came across an issue where I couldn't extend `TextProps`, since it wasn't exported by the lib, which can be seen here:

```tsx
// @vtex/shoreline/dist/index/d.ts 

interface TextOptions {
    /**
     * Text variant
     * @default 'context'
     */
    variant?: 'context' | 'body' | 'action' | 'emphasis' | 'caption1' | 'caption2' | 'display1' | 'display2' | 'display3' | 'display4';
}
interface Label extends TextOptions, ComponentPropsWithoutRef<'label'> {
    as: 'label';
}
interface Paragraph extends TextOptions, ComponentPropsWithoutRef<'p'> {
    as: 'p';
}
interface Div extends TextOptions, ComponentPropsWithoutRef<'div'> {
    as: 'div';
}
interface Li extends TextOptions, ComponentPropsWithoutRef<'li'> {
    as: 'li';
}
interface Span extends TextOptions, ComponentPropsWithoutRef<'span'> {
    as?: 'span';
}
type TextProps = Span | Label | Paragraph | Div | Li;
```

From my understanding it'd be appealing to have it exported, to allow its types to be inherited, rather than shallow-copy it from the component level, which ended up being the solution I've came up with:

```tsx
// status-text.tsx

interface StatusTextProps {
  status?: string
  className?: string
  variant: TextProps['variant'] // This works because, even though TextProps isn't extendable, I can access its properties directly
  children: React.ReactNode
}
```

### Expected behavior

I should be able to import `TextProps` and extend it on any interface on the module level.

### Reproducible Example

https://codesandbox.io/p/sandbox/romantic-lovelace-42n5dn

### Suggested solution

Export `TextProps` so it can be accessed on the project level.

### Package

@vtex/shoreline

### Packages version

^1.4.0

### Browser

Arc (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36)

### Package Manager

yarn

**Comment by lafray** [comment]
@lucasaarcoverde we can add this export? Move this to backlog

**Comment by matheusps** [comment]
Yes, we can!

**Comment by lafray** [comment]
I went to do it and it was already fixed. I changed it to done
