### ISSUE TITLE
StatusText component

### ISSUE THREAD

**Issue by vaporwavie** [vtex/shoreline#1855]
### Summary

Similar to the `Text` component, `StatusText` would extend its DX by allowing color-based statuses to its original API, where said colors will be controlled by built-in statuses or customizable by the developer.

### Minimal example
```tsx
import { StatusText } from '@vtex/shoreline'

export default function MinimalExample() {
  return <StatusText status="warning" variant="action">Hey be careful!</StatusText>
}
```

### Rationale

It would prevent custom handlers to be created around the `Text` component to address that specific matter.

**Comment by vaporwavie** [comment]
@matheusps I can definitely work on this if there's room for the idea 😄

**Comment by matheusps** [comment]
@vaporwavie, Instead for creating a new component - we can add the `color` prop. It accepts a string, that is either a variable or a custom value.

For example:

```jsx
<Text color="var(--sl-color-blue-6)">My blue text</Text>
```

What do you think? 

cc @davicostalf , @lucasaarcoverde

**Comment by vaporwavie** [comment]
@matheusps that also works! I can get it started if it's okay to you guys.
