### ISSUE TITLE
Should we make reference to the issue on the commit description?

### ISSUE THREAD

**Issue by viniciuslagedo** [vtex/shoreline#1857]
### How can we help?

I started making some PRs here and noticed that when running the pnpm commit command, at a certain point, the wizard asks if the commit is related to any issue. I referenced the issue in question, and everything is fine.

However, I now think the issue timeline might become cluttered because we can reference the issue directly in the PR.
Here's an example of the timeline with the double reference:

<img width="862" alt="Captura de Tela 2024-08-22 às 12 15 46" src="https://github.com/user-attachments/assets/3496f6be-6aca-4a38-870d-4cb8abea3c25">

What do you think about it? Should we enforce the reference on the PR and stop making it in the commit? Or should we keep using it this way? Is that even a problem?

**Comment by lafray** [comment]
Até onde sei. Esse repositório utiliza Learn para fazer o changelog. E o learn usa os commits para obter informações para o changelog. Então nesse sentido acho importante manter a nível de commit.
Outro ponto que tenho é que quando estamos mechendo no código, vemos a informação da origem da mudança mais no commit. Nesse sentido eu particularmente acho que tem muito valor a referência no commit

**Comment by viniciuslagedo** [comment]
Faz sentido esses pontos! Olhando nessa ótica eu manteria nos commits também.

**Comment by lafray** [comment]
@viniciuslagedo Acha que seria o caso de fecharmos a issue?

**Comment by viniciuslagedo** [comment]
Por mim sim, mas não sei se mais gente tem algo pra contribuir. Cc: @lucasaarcoverde  @matheusps

**Comment by lucasaarcoverde** [comment]
SIm, como vocês apontaram é realmente valioso ter a ref no commit! Isso também ajuda a abrir o PR já com a issue referenciada, o que faz com que ela mova a issue para "Done" assim que o PR for mergeado. 

Vou criar um card para adicionarmos essa observação na documentação
