### ISSUE TITLE
Build of the doc site is broken

### ISSUE THREAD

**Issue by kevinch** [vtex/shoreline#1859]
### Problem

While trying to build the documentation site with `pnpm build:docs`, I receive several errors with a finale failure.

The errors are related for most part to the contributors system:

```
Error occurred prerendering page "/guides/contributor/viniciuslagedo". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading 'stats')
    at ContributorStats (/Users/kevin.chevallier/Repos/tests/shoreline/packages/docs/.next/server/chunks/414.js:1883:257680)
```

There is also a Sentry related error:

```
error - No Sentry auth token configured. Source maps will not be uploaded.
```

![Screenshot 2024-08-22 at 14 54 59](https://github.com/user-attachments/assets/8ea4f841-3c51-4592-b952-7978470358c9)

This has been performaed on a brand new clone & install of the project today right before creatinbg the issue. 

Node 21

### Browser

n/a

### Package Manager

pnpm

**Comment by lucasaarcoverde** [comment]
> Error occurred prerendering page "/guides/contributor/viniciuslagedo". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading 'stats')
    at ContributorStats (/Users/kevin.chevallier/Repos/tests/shoreline/packages/docs/.next/server/chunks/414.js:1883:257680)

This error occurs because when running the build is necessary to have a GitHub token defined as an environment variable

**Comment by lucasaarcoverde** [comment]
I don't see the `Sentry` error breaking the project, I didn't configure this token locally and it works well for me. 
Probably this pr #1860 will solve this problem

**Comment by kevinch** [comment]
Here's a log of the Sentry error after a `pnpm build:docs` test right now:

<img width="883" alt="Screenshot 2024-08-23 at 11 29 01" src="https://github.com/user-attachments/assets/4e39fcf3-6481-44a7-b07e-86fffa41f7dd">
