### ISSUE TITLE
Add line chart to shoreline components

### ISSUE THREAD

**Issue by gabriellymoura** [vtex/shoreline#1867]
### Summary

The line chart is the most common chart used in apps that need analytics dashboards.  It's necessary always to create a new component and follow the right template. Some apps that use a line chart:

- The admin home ([cea case](https://cea.myvtex.com/admin))
<img width="457" alt="image" src="https://github.com/user-attachments/assets/7d2de154-41bc-4270-adee-76e0c5335550">

- The admin sales performance ([cea case](https://cea.myvtex.com/admin/sales-performance/?viewId=6e0a40c4-546d-11ec-82ac-16e0966f28c9))
<img width="1200" alt="image" src="https://github.com/user-attachments/assets/6898f008-48a3-41ed-8605-760b0b5809ce">

- The [Health Monitor](https://healthmonitor.vtex.com/)
<img width="1126" alt="image" src="https://github.com/user-attachments/assets/08cc3783-84e4-4e75-90c8-a8802f2bbdec">

### Rationale

The shoreline could include this component to make charts part of the VTEX design system and serve as a base for frontend projects. I made an [RFC](https://docs.google.com/document/d/1iJDImFt87OyjLh36VoZLpAbInMTyOifamcVY8YOjvcI/edit?usp=sharing) that tells more about some issues faced in the development with charts and the best solution.

**Comment by beatrizmilhomem** [comment]
Hello @gabriellymoura ! This issue is already being addressed in two different issues:
https://github.com/vtex/shoreline/issues/1700 – design
https://github.com/vtex/shoreline/issues/1636 – implementation
Please, feel free to contribute to any of them. I'm closing this one for now.
