### ISSUE TITLE
Menu/Tooltip: property types are obligatory in typescript 4.x

### ISSUE THREAD

**Issue by viniciuslagedo** [vtex/shoreline#1877]
### Problem

After updating our project shoreline version to the latest ("1.2.0"), the `Menu` and `Tooltip` components began emitting an error:
"missing the following properties from type 'MenuOptions': open, setOpen, defaultOpen, store, placement"

These properties exist, and they come from `ariakit`, but should be optional. We discovered this doesn't happen in typescript `5.x`, but this is a problem in the version installed in our project (`typescript@4.9.5`). Since shoreline doesn't have a peer dependency to `typescript` and this problem didn't happen in `shoreline@0.x`, this is probably a bug within `shoreline` or `ariakit`.

### Package

@vtex/shoreline

### Package Manager

yarn

**Comment by davicostalf** [comment]
Aligned with @matheusps that typescript 5.x should be added as a peer dependency.
