### ISSUE TITLE
Setting Search value to "undefined" crashes the "cleaning" behavior

### ISSUE THREAD

**Issue by riccoutinho** [vtex/shoreline#1895]
### Problem

When the value of the `Search` component is set to `undefined`, the `onClear` behavior does not work properly.  
The function passed to the `onClear` prop is called but the Input value on the component is not erased.
```
      <Search
        value={undefined}
        onChange={(event) => handleOnChange(event)}
        onClear={handleOnClear}
      />
```

### Expected behavior

When clicking the `X` button to clear, the `onClear` function should be called and the component should not display the string anymore

### Reproducible Example
[Codesandbox example](https://codesandbox.io/p/sandbox/fast-water-fm9fv2?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0csi43200063b6mdc702kpu%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0csi43100023b6m2wi3kf6r%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0csi43200033b6mn4mujc06%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0csi43200053b6max2hu5b8%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0csi43100023b6m2wi3kf6r%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0csi43100013b6m0xuqxyf1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm0csi43100023b6m2wi3kf6r%2522%252C%2522activeTabId%2522%253A%2522cm0csi43100013b6m0xuqxyf1%2522%257D%252C%2522cm0csi43200053b6max2hu5b8%2522%253A%257B%2522id%2522%253A%2522cm0csi43200053b6max2hu5b8%2522%252C%2522activeTabId%2522%253A%2522cm0csvzlh006k3b6l4eqbbbnj%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0csi43200043b6mo634bwky%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm0csjmvg00153b6lrbmdjd77%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522isCloud%2522%253Afalse%252C%2522id%2522%253A%2522cm0csvzlh006k3b6l4eqbbbnj%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm0csi43200033b6mn4mujc06%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm0csi43200033b6mn4mujc06%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Package Manager

yarn

**Comment by lucasaarcoverde** [comment]
Good catch @riccoutinho! I'll move the Issue to the Backlog. Feel free to solve it if you want 😄

**Comment by viniciuslagedo** [comment]
Hi Ricardo. This behavior happens just as expected. The same would happen if you used an <input> instead of the <Search> component. Try it out!

It happens because `undefined` has a special meaning to React: it is the same as not passing the value property, which makes the component uncontrolled. Making the component uncontrolled does not clear the text—you can use an empty string instead.

**Comment by davicostalf** [comment]
@riccoutinho I've validated what @viniciuslagedo said with @matheusps, so I'm closing this issue. But feel free to revisit this if there any questions left.
