### ISSUE TITLE
How to make TsTable columns width be dynamic?

### ISSUE THREAD

**Issue by luarakerlen** [vtex/shoreline#1923]
### How can we help?

I'm using TsTable component to create a table, and I need to define width according to [Figma specifications](https://www.figma.com/design/FzUpFEwsQAkTV5nF6JcLYU/Campaigns-and-Reports-2?node-id=429-34481&t=61DuDpU7mHaDM7y1-4):

<img width="1295" alt="image" src="https://github.com/user-attachments/assets/52f4ffd1-829c-4dbe-bde0-21ddf0a7d981">

Columns width need to be dynamics, receiving a min and a max value, being the max value, part of a grid template. How can I do this?

### What have you tried?

Currently I'm specifying a fixed width using columnsWith like this:
```javascript
 <TsTable
    data={data}
    columns={columns}
    columnWidths={columns.map((column) =>
      !!column.width ? column.width : 'auto'
    )}
    ...
/>
```

Columns:
```javascript
const columns: Column<Report>[] = useMemo(
  () => [
    {
      id: 'title',
      width: '500px',
      ...
    },
    ...
  ],
  []
  )

```

Column type:
```javascript
export type Column<TData> = ColumnDef<TData, any> & {
  width?: string
  ...
}
```

### Additional information

PR with modifications: https://github.com/vtex/admin-ads/pull/127/files

**Comment by matheusps** [comment]
You can use the `minmax()` query on the width property

**Comment by luarakerlen** [comment]
I just tried it. It seems table always get max width value and some columns don't appear if we don't scroll:


https://github.com/user-attachments/assets/23368cd1-1245-4288-b7c4-666fb3c03b58




If you have access, I create [this workspace](https://pr127--paguemenosvtexads.myvtex.com/admin/ads-for-advertisers/reports) to see how is the behavior. You need to create some reports to see the table.

@davicostalf can you test it there?

**Comment by davicostalf** [comment]
Maybe the issue is related to this:
<img width="395" alt="image" src="https://github.com/user-attachments/assets/58c08575-341b-4374-a9e4-572392ac6015">

It seems like the default was not overwritten.

**Comment by matheusps** [comment]
My mistake, this `width` prop is not accepted by the hook. There is a `columnWidths` property for this: https://codesandbox.io/p/sandbox/sftvnc?file=%2Fsrc%2FApp.tsx%3A46%2C42. Sorry for the late response.

**Comment by matheusps** [comment]
Added this issue on our backlog for better documentation: https://github.com/vtex/shoreline/issues/1933.

**Comment by luarakerlen** [comment]
@matheusps I can't open this code. I'm receiving this message:

<img width="547" alt="image" src="https://github.com/user-attachments/assets/eff53455-6558-45b0-b49d-aadae581d75e">
