### ISSUE TITLE
Default color in Text component

### ISSUE THREAD

**Issue by lafray** [vtex/shoreline#1931]
### Problem

Ao utilizar o componente Text, espera-se que ele tenha um comportamento semelhante ao span porém garantindo que os estilos do Shoreline estão aplicados. Nesse sentido, espera-se que a cor por padrão seja `inherit`. Porém não está sendo o comportamento atual.

[Nesta PR](https://github.com/vtex/shoreline/pull/1908) que adiciona o campo color ao componente para resolver [esta issue](https://github.com/vtex/shoreline/issues/1855) configurou a cor padrão para preto, quebrando o comportamento que se tinha antes no componente

### Expected behavior

Espera-se que no cenário a baixo o a palabre destaque ainda estivesse na cor verde mas não é o que ocorre.

```
<Text color="var(--sl-fg-success)">
    Algum texto para sucesso com uma parte com
   <Text variant="emphasis">em destaque</Text>
</Text>
```

Isso obriga o utilizador da lib a ficar forçando a cor de cada children

### Suggested solution

Na [linha 14](https://github.com/vtex/shoreline/blob/3eb6adc2cfcab0279d63eec73214620c9694dcd5/packages/shoreline/src/components/text/text.tsx#L14) em Text.tsx mudar o valor padrão para `inherit`

### Package Manager

pnpm

**Comment by lafray** [comment]
@lucasaarcoverde @matheusps vcs estão de acordo?

**Comment by matheusps** [comment]
De acordo @lafray
