### ISSUE TITLE
Page header with inconsistent height in Figma and Code

### ISSUE THREAD

**Issue by felipepowlist** [vtex/shoreline#1951]
### Problem

The height of the page header is not consistent and causing miscommunication between front-end and design. 

**[Figma](https://www.figma.com/design/PWGSQ26U55u8E34JWn9ZYE/Shoreline-%E2%80%93-Components?node-id=1959-126901&t=plZyxAJv206uyVUq-4)**
<img width="1322" alt="Captura de Tela 2024-09-13 às 14 33 28" src="https://github.com/user-attachments/assets/54d19f95-023f-444c-96f1-33c521e7bcbf">

**[Shoreline documentation](https://shoreline.vtex.com/components/page)**
![image](https://github.com/user-attachments/assets/ca6071a3-1e0e-4722-ad57-a289590e134a)

### Suggested solution

I believe we should follow the specification on Figma

### Package Manager

pnpm

**Comment by davicostalf** [comment]
Hi @felipepowlist! The page header styles are responsive:
<img width="1032" alt="image" src="https://github.com/user-attachments/assets/567695de-d536-42ee-81ba-a6afa222f7e3">

As can be seen in Figma as well:
<img width="958" alt="image" src="https://github.com/user-attachments/assets/c8d9e999-06df-47f3-b5ae-72871dea4a29">

- When it's width is equal or less than 379px, it's corresponding height is 72px.
- When it's width is between 380px and 559px, it's corresponding height is 80px (in code but not in Figma, I'm looking into this).
- When it's width is between 560px and 799px, it's corresponding height is 88px.
- When it's width is equal or above 800px, it's corresponding height is 96px.

That is to say, it's behaving in code as intended. Do you think we choose change this behavior?

**Comment by felipepowlist** [comment]
Got it!! 

I guess we could make this behavior more clear in the documentation. I only noticed the width prop in Figma now that you explained it to me. 

Also, should we have a prop in Figma for the layout (wide, standard, narrow)?

**Comment by davicostalf** [comment]
> I guess we could make this behavior more clear in the documentation. I only noticed the width prop in Figma now that you explained it to me.
In the Page best practices documentation you mean? Since it's something that "just works" we avoided including additional content. At least to me, it seems most designers use the Page Header through the Page component, and there it's already configured as it should be. Do you see it differently?

> Also, should we have a prop in Figma for the layout (wide, standard, narrow)?
Layout is a prop of the PageContent component. In Figma, since PageContent doesn't exist as a standalone component, the prop was added in the page component. Does it make sense to you?

**Comment by davicostalf** [comment]
Thanks, @felipepowlist! We'll continue to discuss this in the issue #1790.
