### ISSUE TITLE
Exportar os types das propriedades dos componentes 

### ISSUE THREAD

**Issue by ArthurFerrao** [vtex/shoreline#1954]
### How can we help?

Penso que seria interessante exportar os tipos das props de alguns componentes. Hoje temos algumas propriedades de componentes que não exportam seus tipos e são adicionadas diretamente na interface. Acham que faz sentido?

### What have you tried?

O componente `Text` tem a propriedade `variant` que não tem type exportado pela shoreline, dessa forma, foi necessário criar em código esse type para poder passa-lo através de props.
Percebi que isso ocorre para outros componentes que possuem propriedade `variant`, além de outras props que também não são exportadas em alguns componentes.

**Comment by lucasaarcoverde** [comment]
Opa @ArthurFerrao qual os casos que você não consegue acessar as propriedades? Pelo código estamos exportando as props do Text e também testei num [codesandbox](https://codesandbox.io/p/sandbox/yw3ggl) e ta retornando certinho os tipos

Os componentes deveriam sim exportar as propriedades, em alguns casos a gente não exporta, mas deveria e ai é só abrir um PR ou issue identificando pra consertar

**Comment by ArthurFerrao** [comment]
Obrigado @lucasaarcoverde! Erro meu, não tinha entendido que dava para importar dessa forma. Realmente está funcionando para o Text.
