### ISSUE TITLE
Anchor Component

### ISSUE THREAD

**Issue by vaporwavie** [vtex/shoreline#1966]
### Problem

Currently, Shoreline offers `Link`, which is an agnostic hyperlink handler. It's fantastic and does the job well. My proposal would be also offering a _opinionated_ version called `Anchor`, which would not only be wrapped around `Link`, but also provide a built-in layout, while allowing the user to customize it even more.

### Solution

I've wrote a prototype for this Anchor component [here](https://codesandbox.io/p/sandbox/goofy-anchor-forked-gjncsf). It uses the same design system seen on Faststore Webops, which had its layout recently refined to adequate the same styling seen on Shoreline.

### Usage examples

- The developer wants a built-in solution to render Links without having to deep-dive on a style sheet.
- The developer wants Shoreline's opinion on how a customized Link should behave (a11y ready, responsive-first, etc)

You can also see below how it works on Webops:

https://github.com/user-attachments/assets/2aa942dc-c559-4ad5-b16a-d7aefe0b7c30

### Dependencies

no deps

### References

This was made together with @renatamottam to guarantee that we'd have the best possible outcome following the provided design system.

**Comment by matheusps** [comment]
@beatrizmilhomem, and @davicostalf... Can you take a look at this? Did you see this same behavior on other Admin applications?

**Comment by davicostalf** [comment]
@davicostalf I still haven't seen other scenarios like this. Maybe a tertiary button would work in this scenario 🤔

**Comment by renatamottam** [comment]
I did some testing, we can compare it here:
<img width="1678" alt="image" src="https://github.com/user-attachments/assets/0107cf31-b7a5-4f34-beb0-571cbb8ea77a">

Some potential improvements using this `Anchor` component:
- possibility to use longer labels (buttons shouldn't use long terms as labels)
- possibility to add a `max-width` for labels with `text-ellipsis` at the end
- avoid icon repetition (only show on hover)
- hover status that fits the grid
- smaller height

**Comment by beatrizmilhomem** [comment]
I agree the custom link works better here!

**Comment by beatrizmilhomem** [comment]
@vaporwavie Me, @davicostalf, and @matheusps discussed the issue, and our conclusion was that it doesn't make sense to create a new component or even a variation of the `Link` component right now since there are no other application scenarios. But the proposal hasn't been discarded, and it could be interesting to start doing studies about that.
