### ISSUE TITLE
Contextual helpt min-width

### ISSUE THREAD

**Issue by lafray** [vtex/shoreline#1967]
### Problem

Depois da mudança feita nesta [PR](https://github.com/vtex/shoreline/pull/1955), o min width add [nesta linha](https://github.com/vtex/shoreline/blob/4051aa336de377a43fe6fbcb907b12e85b8c9db0/packages/shoreline/src/themes/sunrise/components/button.css#L13) passou a ser aplicado no botão do contextual help pq ele não é feito com IconButton, para ter o min-width set para `auto` pelo estilo [dessa linha](https://github.com/vtex/shoreline/blob/4051aa336de377a43fe6fbcb907b12e85b8c9db0/packages/shoreline/src/themes/sunrise/components/icon-button.css#L2).

### Expected behavior

Espera-se que o width do botão do contextual help ocupasse o espaço baseado no conteudo

### Reproducible Example

https://shoreline.storybook.vtex.com/?path=/story/components-contextual-help--show&globals=backgrounds.grid:!false;outline:!true

### Suggested solution

Pode-se:
- addicionar `data-sl-icon-button` ao Button instancializado pelo contextual help
Ou
- Trocar o de Button para IconButton o elemento utilizado pelo contextual help
Ou
- Add um style para a `[data-sl-contextual-help-trigger]` que sobreescreva o min-width do botão

### Additional context

<img width="650" alt="image" src="https://github.com/user-attachments/assets/1ce9bd67-03be-4779-aa22-176919b85a20">

### Package Manager

pnpm

**Comment by lafray** [comment]
@matheusps @lucasaarcoverde qual das soluções vocês acham melhor? Só me falarem que ja abro a PR

**Comment by matheusps** [comment]
I would use the IconButton for this solution instead.
