### ISSUE TITLE
Contextual help inside modal

### ISSUE THREAD

**Issue by lafray** [vtex/shoreline#1970]
### Problem

Quando o contextual help é usado dentro de um modal, não é possível vizualizá-lo pois ele é renderizado atrás do modal

### Expected behavior

Contextual help ser henderizado acima do modal

### Reproducible Example

<img width="613" alt="image" src="https://github.com/user-attachments/assets/3a30c5ed-b9fb-40d9-8858-acc76cf8d12a">

### Suggested solution

Mudar o z-index do contextual help popover

### Package Manager

pnpm

**Comment by lafray** [comment]
@matheusps @lucasaarcoverde vocês vem que mudar esse zindez pode trazer outros problemas?

**Comment by matheusps** [comment]
Não vejo problema em mudar o zIndex.
