### ISSUE TITLE
Zindex of elements

### ISSUE THREAD

**Issue by lafray** [vtex/shoreline#1971]
### Problem

Atualmente alguns varios elementos estão implementados com z index diferentes do que esta na documentação

[Documentação](https://shoreline.vtex.com/foundations/elevation/best-practices):
![image](https://github.com/user-attachments/assets/b615774a-2b3b-4f98-b59b-000fd03aff60)

Código:
![image](https://github.com/user-attachments/assets/4913ae86-ca99-4ada-9055-7d80bf7b25ee)

Qual seria o correto? Dependendo de qual for o outro precisa ser atualizado

### Suggested solution

Arruamar a documentação ou atualizar o código para que ambos estejam coerentes

### Package Manager

pnpm

**Comment by lafray** [comment]
Ok, So I will correct all zindex.

**Comment by lafray** [comment]
@davicostalf Qual seria o zindex do menu? não esta na doc. é o mesmo de popover?

**Comment by davicostalf** [comment]
@lafray A gente considera que o que o menu abre é um popover

**Comment by lafray** [comment]
> @lafray A gente considera que o que o menu abre é um popover

Acredito que não seja possivel o z-indez do menu ser o mesmo em todos os cenários. Pq se for o mesmo do popover sempre, e sendo o do popover maior que o do backgroud do modal, em um cenário bem comum como um menu de more actions numa tabela que aber um modal ao clicar na ação tera esse popover acima do modal, gerando um layout estranho. Acho que precisaremos de duas opções de z indez, dependendo do contexto onde é instacializado

**Comment by davicostalf** [comment]
> em um cenário bem comum como um menu de more actions numa tabela que aber um modal ao clicar na ação tera esse popover acima do modal, gerando um layout estranho

o comportamento certo/atual não seria o popover do menu fechar uma vez que a ação é triggada?

> Na verdade, pensando mais a fundo, o proprio popover deveria ter essa mudança de z index em função do contexto. Dado que esse mesmo tipo de conflito pode acontecer em todos os elementos que usam ele como base

será que essa complexidade realmente é necessária? tem algum outro cenário para ilustrar fora esse?

**Comment by lafray** [comment]
> o comportamento certo/atual não seria o popover do menu fechar uma vez que a ação é triggada?

Verdade. Acho que confundi com o comportamento como era no admin-ui.

Acho que não tem nenhum popover hoje que não fechar depois que um clique ocorre

**Comment by lafray** [comment]
> @lafray A gente considera que o que o menu abre é um popover

Hoje no código se configura esse z-index para todos os elementos com popover individualmente, (pois eles não compartilham em código o mesmo elemento). Acho que seria importante ter um token semantico para o z indez do popover para poder ser reutilizados nos lugares e em caso de mudança, poder manter a consistencia de forma fácil, mexendo o valor em um único lugar. Como vocês veem a criação de uma variavél global/token como `--sl-z-popover: var(--sl-z-6)` @matheusps @lucasaarcoverde ?

**Comment by davicostalf** [comment]
Achei que nós tínhamos um componente de popover
