### ISSUE TITLE
useCollapsible hook

### ISSUE THREAD

**Issue by matheusps** [vtex/shoreline#443]
# RFC useCollapsible hook

## Why

The current `collapsible` component does not match the design guidelines. The `card` component can be composed/enhanced to accomplish collapsible content. This proposal means to deprecate the collapsible in favor of a lower-level approach with hooks. This will enhance the flexibility and reuse of disclosure-collapsible behavior. 

## Pros

- Enhance collapsible behavior flexibility.
- Allow collapsible behavior reuse.
- Less component overhead, the Design System API surface area gets smaller.

## Drawbacks

- It gets more complex to learn and apply because the actual use is not attached to a component.
- Migration is needed, and code mods will not help much (good old documentation, them 😀 ).

### Before

We use the `collapsible` component with a state hook.

```jsx
import { useCollapsibleState, Collapsible, CollapsibleHeader, CollapsibleContent } from '@vtex/admin-ui'

function Example() {
  const state = useCollapsibleState()

  return (
    <Collapsible state={state}>
      <CollapsibleHeader label="your label" />
      <CollapsibleContent> your content </CollapsibleContent>
    </Collapsible>
  )
}
```

### After

Replace the `collpasible` with the `useCollapsible` hook, which returns the props (using the prop-getters pattern). 

```jsx
function Example() {
  const { getToggleProps, getCollapseProps } = useCollapsible()

  return (
    <Card>
      <CardHeader {...getToggleProps()}>
        <CardTitle>Your title</CardTitle>
      </CardHeader>
      <CardContent {...getCollapseProps()}>Your content</CardContent>
    </Card>
  )
}
```

#### Abstracting

The developer can abstract the component into a stateful accordion, or whatever makes sense for the application. 

```jsx
// accordion.tsx
interface Props {
  title: ReactNode
  content: ReactNode
}

export function Accordion (props: Props) {
  const { title, content } = props
  const { getToggleProps, getCollapseProps } = useCollapsible()

  return (
    <Card>
      <CardHeader {...getToggleProps()}>
        <CardTitle>{title}</CardTitle>
      </CardHeader>
      <CardContent {...getCollapseProps()}>{content}</CardContent>
    </Card>
  )
}

// usage.tsx
import { Accordion } from './accordion.tsx'

<Accordion title="Your title" content="your content" />
```

_Originally posted by @matheusps in https://github.com/vtex/admin-ui/discussions/438_

**Comment by davicostalf** [comment]
@anitavincent @matheusps This was solved in the last release, right?

**Comment by davicostalf** [comment]
@matheusps This was solved, right?
